catalog:
  vite: 8.0.8
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: 0.1.19
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
