catalog:
  vite: 8.0.8
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: 0.1.19
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  encoding-sniffer: 1.0.2
  node-domexception: link:./vendor/node-domexception
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
