"use client"

/* biome-ignore-all lint/security/noDangerouslySetInnerHtml: syntax highlighting HTML is generated by sugar-high */

import * as React from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { CheckIcon, ChevronRightIcon, CopyIcon } from "lucide-react"

import type { ConversationItem, PromptImage } from "@/lib/pi-web"
import type { HighlightResponse } from "@/lib/pi-web-api"

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

const highlightCache = new Map<
  string,
  Promise<HighlightResponse> | HighlightResponse
>()

const MemoizedReactMarkdown = React.memo(ReactMarkdown)
const MARKDOWN_REMARK_PLUGINS = [remarkGfm]
const MARKDOWN_COMPONENTS = {
  code({ className, children, ...props }) {
    return (
      <code
        className={cn(
          "rounded bg-muted px-1 py-0.5 font-mono text-[0.92em] text-[#f19232] before:content-none after:content-none",
          className
        )}
        {...props}
      >
        {children}
      </code>
    )
  },
  pre({ children }) {
    const codeElement = getCodeBlockChild(children)

    if (!codeElement) {
      return <pre>{children}</pre>
    }

    const code = markdownNodeText(codeElement.props.children).replace(/\n$/, "")
    const language = parseCodeLanguage(codeElement.props.className)

    return <CodeBlock code={code} language={language} />
  },
} satisfies NonNullable<
  React.ComponentProps<typeof ReactMarkdown>["components"]
>

function parseCodeLanguage(className?: string) {
  const match = className?.match(/language-([A-Za-z0-9_+#.-]+)/)
  return match?.[1]
}

const CODE_LANGUAGE_BY_EXTENSION: Record<string, string> = {
  c: "c",
  cc: "c",
  cpp: "c",
  cs: "c",
  css: "css",
  go: "go",
  h: "c",
  htm: "html",
  html: "html",
  java: "java",
  js: "javascript",
  jsx: "jsx",
  json: "json",
  jsonc: "jsonc",
  mjs: "javascript",
  mdx: "mdx",
  py: "python",
  rs: "rust",
  ts: "typescript",
  tsx: "tsx",
  xml: "xml",
}

function codeLanguageFromPath(path: string) {
  const cleanPath = path.split(/[?#]/)[0] || ""
  const extension = cleanPath.match(/\.([A-Za-z0-9]+)$/)?.[1]?.toLowerCase()
  if (!extension) return undefined

  return CODE_LANGUAGE_BY_EXTENSION[extension]
}

function markdownNodeText(node: React.ReactNode): string {
  if (typeof node === "string" || typeof node === "number") {
    return String(node)
  }

  if (Array.isArray(node)) {
    return node.map((child) => markdownNodeText(child)).join("")
  }

  if (React.isValidElement<{ children?: React.ReactNode }>(node)) {
    return markdownNodeText(node.props.children)
  }

  return ""
}

async function getHighlightedCode(code: string, language?: string) {
  if (!language) {
    return {
      ok: true,
      skipped: true,
    } satisfies HighlightResponse
  }

  const cacheKey = `${language}\u0000${code}`
  const cached = highlightCache.get(cacheKey)
  if (cached) {
    return await cached
  }

  const promise = fetch("/api/highlight", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ code, language }),
  }).then(async (response) => {
    const payload = (await response.json()) as HighlightResponse
    return payload
  })

  highlightCache.set(cacheKey, promise)
  const payload = await promise
  highlightCache.set(cacheKey, payload)
  return payload
}

const CodeBlock = React.memo(function CodeBlock({
  code,
  language,
}: {
  code: string
  language?: string
}) {
  const [highlighted, setHighlighted] =
    React.useState<HighlightResponse | null>(null)
  const [copyState, setCopyState] = React.useState<"idle" | "copied" | "error">(
    "idle"
  )

  React.useEffect(() => {
    let cancelled = false

    if (!language) {
      setHighlighted(null)
      return
    }

    setHighlighted(null)
    void getHighlightedCode(code, language)
      .then((payload) => {
        if (!cancelled) {
          setHighlighted(payload)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setHighlighted({ ok: true, unavailable: true })
        }
      })

    return () => {
      cancelled = true
    }
  }, [code, language])

  const renderedLanguage =
    highlighted && "language" in highlighted && highlighted.language
      ? highlighted.language
      : language

  const copyCode = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopyState("copied")
      window.setTimeout(() => setCopyState("idle"), 1400)
    } catch {
      setCopyState("error")
      window.setTimeout(() => setCopyState("idle"), 1400)
    }
  }

  const highlightedHtml = hasHighlightHtml(highlighted)
    ? highlighted.html
    : null

  const highlightedMarkup = { __html: highlightedHtml || "" }

  const highlightedContent = highlightedHtml ? (
    <code
      className={cn(renderedLanguage && `language-${renderedLanguage}`)}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: syntax highlighting HTML is generated by sugar-high
      dangerouslySetInnerHTML={highlightedMarkup}
    />
  ) : null

  return (
    <div className="not-prose overflow-hidden rounded-xl border bg-muted/40">
      <div className="flex items-center justify-between gap-3 border-b bg-background/80 px-3 py-2 text-xs text-muted-foreground">
        <div className="truncate font-medium tracking-wide uppercase">
          {renderedLanguage || "code"}
        </div>
        <Button variant="ghost" size="xs" onClick={copyCode}>
          {copyState === "copied" ? (
            <CheckIcon data-icon="inline-start" />
          ) : (
            <CopyIcon data-icon="inline-start" />
          )}
          {copyState === "copied"
            ? "Copied"
            : copyState === "error"
              ? "Retry"
              : "Copy"}
        </Button>
      </div>
      <pre className="overflow-x-auto bg-transparent px-4 py-3 text-[13px] leading-6 text-foreground">
        {highlightedContent || <code>{code}</code>}
      </pre>
    </div>
  )
})

function isHighlightSkipped(payload: HighlightResponse) {
  return (
    "skipped" in payload ||
    "unsupported" in payload ||
    "unavailable" in payload ||
    ("ok" in payload && payload.ok === false)
  )
}

function isHighlightUnavailable(payload: HighlightResponse) {
  return "unavailable" in payload || ("ok" in payload && payload.ok === false)
}

function hasHighlightHtml(
  payload: HighlightResponse | null
): payload is Exclude<
  HighlightResponse,
  { ok: false; error: string; routePath?: string }
> & { html: string } {
  return Boolean(
    payload && !isHighlightSkipped(payload) && !isHighlightUnavailable(payload)
  )
}

function getCodeBlockChild(children: React.ReactNode) {
  const child = React.Children.toArray(children).find((node) =>
    React.isValidElement<{ children?: React.ReactNode; className?: string }>(
      node
    )
  )

  if (
    !React.isValidElement<{
      children?: React.ReactNode
      className?: string
    }>(child)
  ) {
    return null
  }

  return child
}

const STREAMING_MARKDOWN_PLAIN_TEXT_THRESHOLD = 1200
const STREAMING_MARKDOWN_PROFILE_THRESHOLD_MS = 16

function shouldLogMarkdownProfile() {
  if (typeof window === "undefined") return false
  return window.localStorage.getItem("pi-web-profile-markdown") === "1"
}

const MarkdownBlock = React.memo(function MarkdownBlock({
  streaming = false,
  text,
}: {
  streaming?: boolean
  text: string
}) {
  const useStreamingPlainText =
    streaming && text.length >= STREAMING_MARKDOWN_PLAIN_TEXT_THRESHOLD
  const renderStartedAt =
    typeof performance !== "undefined" ? performance.now() : 0

  React.useLayoutEffect(() => {
    if (!streaming || useStreamingPlainText || !shouldLogMarkdownProfile()) {
      return
    }

    const duration = performance.now() - renderStartedAt
    if (duration < STREAMING_MARKDOWN_PROFILE_THRESHOLD_MS) return

    console.debug("[pi-web] streaming markdown render", {
      durationMs: Math.round(duration),
      length: text.length,
    })
  })

  if (useStreamingPlainText) {
    return (
      <div className="text-sm leading-6 wrap-break-word whitespace-pre-wrap">
        {text}
      </div>
    )
  }

  return (
    <div className="prose prose-sm max-w-none wrap-break-word dark:prose-invert prose-headings:font-semibold prose-p:my-2 prose-pre:m-0 prose-ol:my-2 prose-ul:my-2">
      <MemoizedReactMarkdown
        remarkPlugins={MARKDOWN_REMARK_PLUGINS}
        components={MARKDOWN_COMPONENTS}
      >
        {text}
      </MemoizedReactMarkdown>
    </div>
  )
})

export function promptImageKey(
  image: Pick<PromptImage, "previewUrl" | "data">
) {
  return `${image.previewUrl}:${image.data.slice(0, 24)}`
}

function toolArgsKey(args: unknown) {
  if (typeof args === "string") return args
  if (args == null) return ""

  try {
    return JSON.stringify(args)
  } catch {
    return ""
  }
}

function assistantBlockKey(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  switch (block.type) {
    case "text":
      return `text:${block.text}`
    case "thinking":
      return `thinking:${block.text}`
    case "tool":
      return `tool:${block.callId || block.name || "tool"}:${toolArgsKey(block.args)}`
    case "compaction":
      return `compaction:${block.tokensBefore}:${block.summary}`
    default:
      return "block"
  }
}

export function conversationItemSignature(item: ConversationItem) {
  if (item.kind === "user") {
    return `user:${item.pendingId || ""}:${item.text}:${item.images
      .map((image) => promptImageKey(image))
      .join(",")}:${item.streamingBehavior || ""}:${item.queued ? "1" : "0"}`
  }

  return `assistant:${item.blocks.map((block) => assistantBlockKey(block)).join("|")}:${
    item.streaming ? "1" : "0"
  }`
}

function userMessageLabel(item: Extract<ConversationItem, { kind: "user" }>) {
  if (item.streamingBehavior === "steer") return "Steer"
  if (item.queued || item.streamingBehavior === "followUp") return "Queue"
  return ""
}

function toolDisplayName(name?: string) {
  switch (name) {
    case "bash":
      return "Shell"
    case "read":
      return "Read"
    case "write":
      return "Write"
    case "edit":
      return "Edit"
    case "grep":
      return "Search"
    case "glob":
      return "Glob"
    case "find":
      return "Find"
    case "rg":
      return "Ripgrep"
    case "ls":
    case "list":
      return "List"
    default:
      return name || "Tool"
  }
}

function normalizeToolArgs(args: unknown) {
  if (!args) return undefined
  if (typeof args === "object") {
    return args as Record<string, unknown>
  }
  if (typeof args !== "string") return undefined

  try {
    const parsed = JSON.parse(args)
    return parsed && typeof parsed === "object"
      ? (parsed as Record<string, unknown>)
      : undefined
  } catch {
    return undefined
  }
}

function getToolArgText(
  args: Record<string, unknown> | undefined,
  key: string
) {
  const value = args?.[key]
  return typeof value === "string" && value.trim() ? value.trim() : ""
}

function toolCommandPreview(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  if (typeof block.args === "string" && block.args.trim()) {
    return block.args.trim()
  }

  const args = normalizeToolArgs(block.args)
  return (
    getToolArgText(args, "description") ||
    getToolArgText(args, "command") ||
    getToolArgText(args, "path") ||
    getToolArgText(args, "filePath")
  )
}

function toolReadLocation(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  const args = normalizeToolArgs(block.args)
  const filePath =
    getToolArgText(args, "path") || getToolArgText(args, "filePath")
  const offset = args?.offset
  const limit = args?.limit

  if (typeof offset === "number" && typeof limit === "number" && limit > 0) {
    return `${filePath}:${offset}-${offset + limit - 1}`
  }
  if (typeof offset === "number") {
    return `${filePath}:${offset}`
  }
  if (typeof limit === "number" && limit > 0) {
    return `${filePath} limit=${limit}`.trim()
  }
  return filePath
}

function toolFilePath(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  const args = normalizeToolArgs(block.args)
  return getToolArgText(args, "path") || getToolArgText(args, "filePath")
}

function collapseToolPreview(text: string) {
  return text.replace(/\s+/g, " ").trim()
}

function toolSummary(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""
  const preview =
    block.name === "read" ? toolReadLocation(block) : toolCommandPreview(block)
  if (preview) return collapseToolPreview(preview)
  if (block.running) return "Running"
  if (block.isError) return "Failed"
  return "Done"
}

function formatToolArgString(value: string) {
  const trimmed = value.trim()
  if (!trimmed) return ""

  try {
    const parsed = JSON.parse(trimmed)
    if (parsed && typeof parsed === "object") {
      return JSON.stringify(parsed, null, 2)
    }
  } catch {
    // fall through to the raw string below
  }

  return trimmed
}

function rawShellCommandText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool" || block.name !== "bash") return ""

  if (typeof block.args === "string") {
    const trimmed = block.args.trim()
    if (!trimmed) return ""

    try {
      const parsed = JSON.parse(trimmed)
      if (parsed && typeof parsed === "object" && "command" in parsed) {
        const command = (parsed as Record<string, unknown>).command
        return typeof command === "string" ? command.trim() : trimmed
      }
    } catch {
      return trimmed
    }

    return trimmed
  }

  const args = normalizeToolArgs(block.args)
  return getToolArgText(args, "command") || toolCommandPreview(block)
}

function toolCallText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  if (block.name === "bash") {
    const command = rawShellCommandText(block)
    return command ? `$ ${command}` : ""
  }

  if (typeof block.args === "string") {
    return formatToolArgString(block.args)
  }

  if (block.args == null) return ""

  try {
    return JSON.stringify(block.args, null, 2) || ""
  } catch {
    return ""
  }
}

function toolDiffText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool" || block.name !== "edit") return ""

  return block.details &&
    typeof block.details === "object" &&
    "diff" in block.details &&
    typeof block.details.diff === "string"
    ? block.details.diff.trimEnd()
    : ""
}

function toolOutputText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  const parts: Array<string> = []
  const diff = toolDiffText(block)
  const output = block.output.trimEnd()

  if (diff) {
    parts.push(diff)
  }

  if (output && (!diff || output !== diff)) {
    parts.push(output)
  }

  if (parts.length > 0) {
    return parts.join("\n\n")
  }

  if (block.running) return "Running…"
  if (block.isError) return "Tool failed with no output."
  return "No output available."
}

const EXPLORE_TOOL_NAMES = new Set([
  "read",
  "grep",
  "glob",
  "find",
  "ls",
  "list",
  "rg",
])
const EXPLORE_SHELL_COMMAND_NAMES = new Set(["find", "grep", "ls", "rg"])
const SKIPPABLE_SHELL_COMMAND_NAMES = new Set(["cd", "export", "pwd", "set"])
const SHELL_COMMAND_WRAPPER_NAMES = new Set([
  "command",
  "env",
  "noglob",
  "sudo",
  "time",
])

type AssistantConversationBlock = Extract<
  ConversationItem,
  { kind: "assistant" }
>["blocks"][number]

type AssistantToolBlock = AssistantConversationBlock & { type: "tool" }

type AssistantBlockGroup =
  | {
      type: "block"
      key: string
      block: AssistantConversationBlock
    }
  | {
      type: "explore"
      key: string
      blocks: Array<AssistantToolBlock>
    }

type AssistantBlockGroupDescriptor =
  | {
      type: "block"
      key: string
      blockKey: string
    }
  | {
      type: "explore"
      key: string
      blockKeys: Array<string>
    }

type AssistantBlockStoreSnapshot = {
  blockByKey: Map<string, AssistantConversationBlock>
  groups: Array<AssistantBlockGroupDescriptor>
  revision: number
}

type AssistantBlockStore = {
  getBlock: (key: string) => AssistantConversationBlock | undefined
  getBlocks: (keys: Array<string>) => Array<AssistantConversationBlock>
  getGroups: () => Array<AssistantBlockGroupDescriptor>
  setBlocks: (blocks: Array<AssistantConversationBlock>) => void
  subscribe: (listener: () => void) => () => void
  subscribeBlocks: (keys: Array<string>, listener: () => void) => () => void
}

function shellCommandNameFromSegment(segment: string) {
  let text = segment.trim()

  while (text) {
    const assignmentMatch = text.match(/^[A-Za-z_][A-Za-z0-9_]*=\S+\s+/)
    if (assignmentMatch) {
      text = text.slice(assignmentMatch[0].length).trimStart()
      continue
    }

    const commandMatch = text.match(/^([./A-Za-z0-9_-]+)\b/)
    if (!commandMatch) return ""

    const commandPath = commandMatch[1] || ""
    const commandName = pathBaseName(commandPath)

    if (!SHELL_COMMAND_WRAPPER_NAMES.has(commandName)) {
      return commandName
    }

    text = text.slice(commandPath.length).trimStart()
  }

  return ""
}

function exploreShellCommandName(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool" || block.name !== "bash") return ""

  const command = rawShellCommandText(block)
  const segments = command.split(/(?:&&|\|\||;)/)

  for (const segment of segments) {
    const commandName = shellCommandNameFromSegment(segment)
    if (!commandName || SKIPPABLE_SHELL_COMMAND_NAMES.has(commandName)) {
      continue
    }

    return EXPLORE_SHELL_COMMAND_NAMES.has(commandName) ? commandName : ""
  }

  return ""
}

function isExploreToolBlock(
  block: AssistantConversationBlock
): block is AssistantToolBlock {
  if (block.type !== "tool") return false
  return (
    EXPLORE_TOOL_NAMES.has(block.name || "") ||
    Boolean(exploreShellCommandName(block))
  )
}

function getToolArgNumber(
  args: Record<string, unknown> | undefined,
  key: string
) {
  const value = args?.[key]
  const numberValue =
    typeof value === "number"
      ? value
      : typeof value === "string" && value.trim()
        ? Number(value)
        : Number.NaN

  return Number.isFinite(numberValue) ? numberValue : undefined
}

function pathBaseName(path: string) {
  const normalized = path.replace(/\\/g, "/").trim()
  if (!normalized) return ""

  const parts = normalized.split("/")
  return parts[parts.length - 1] || normalized
}

function formatExploreArg(
  key: string,
  value: string | number | undefined
): string {
  if (value == null) return ""

  const text =
    typeof value === "number" ? String(value) : collapseToolPreview(value)

  return text ? `${key}=${text}` : ""
}

function formatExploreCount(
  count: number,
  singular: string,
  plural = `${singular}s`
) {
  return `${count} ${count === 1 ? singular : plural}`
}

function exploreGroupSummary(
  blocks: Array<
    Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
      type: "tool"
    }
  >
) {
  let readCount = 0
  let searchCount = 0
  let listCount = 0

  for (const block of blocks) {
    if (block.name === "read") {
      readCount += 1
      continue
    }
    const shellCommandName = exploreShellCommandName(block)
    if (
      block.name === "ls" ||
      block.name === "list" ||
      shellCommandName === "ls"
    ) {
      listCount += 1
      continue
    }
    searchCount += 1
  }

  return [
    readCount > 0 ? formatExploreCount(readCount, "read") : "",
    searchCount > 0 ? formatExploreCount(searchCount, "search") : "",
    listCount > 0 ? formatExploreCount(listCount, "list") : "",
  ]
    .filter(Boolean)
    .join(", ")
}

function exploreGroupStatusLabel() {
  return "Explore"
}

function exploreToolLine(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
    type: "tool"
  }
) {
  const args = normalizeToolArgs(block.args)
  const path =
    getToolArgText(args, "path") || getToolArgText(args, "filePath") || "/"
  const status = block.running ? "Running" : block.isError ? "Failed" : ""

  switch (block.name) {
    case "read":
      return {
        label: "Read",
        details: [
          pathBaseName(path) || path,
          formatExploreArg("offset", getToolArgNumber(args, "offset")),
          formatExploreArg("limit", getToolArgNumber(args, "limit")),
          status,
        ]
          .filter(Boolean)
          .join("  "),
      }
    case "grep":
    case "rg":
      return {
        label: block.name === "rg" ? "Ripgrep" : "Grep",
        details: [
          path,
          formatExploreArg(
            "pattern",
            getToolArgText(args, "pattern") || getToolArgText(args, "query")
          ),
          formatExploreArg("include", getToolArgText(args, "include")),
          status,
        ]
          .filter(Boolean)
          .join("  "),
      }
    case "glob":
      return {
        label: "Glob",
        details: [
          path,
          formatExploreArg("pattern", getToolArgText(args, "pattern")),
          status,
        ]
          .filter(Boolean)
          .join("  "),
      }
    case "find":
      return {
        label: "Find",
        details: [
          path,
          formatExploreArg(
            "pattern",
            getToolArgText(args, "pattern") ||
              getToolArgText(args, "query") ||
              getToolArgText(args, "name")
          ),
          formatExploreArg("limit", getToolArgNumber(args, "limit")),
          status,
        ]
          .filter(Boolean)
          .join("  "),
      }
    case "ls":
    case "list":
      return {
        label: "List",
        details: [
          path,
          formatExploreArg("limit", getToolArgNumber(args, "limit")),
          status,
        ]
          .filter(Boolean)
          .join("  "),
      }
    case "bash": {
      const shellCommandName = exploreShellCommandName(block)
      const label =
        shellCommandName === "rg"
          ? "Ripgrep"
          : shellCommandName === "ls"
            ? "List"
            : shellCommandName
              ? `${shellCommandName[0]?.toUpperCase()}${shellCommandName.slice(1)}`
              : "Shell"

      return {
        label,
        details: [collapseToolPreview(rawShellCommandText(block)), status]
          .filter(Boolean)
          .join("  "),
      }
    }
    default:
      return {
        label: toolDisplayName(block.name),
        details: toolSummary(block),
      }
  }
}

function assistantBlockRenderKey(
  block: AssistantConversationBlock,
  index: number
) {
  return block.blockKey || `${assistantBlockKey(block)}:${index}`
}

function groupAssistantBlocks(blocks: Array<AssistantConversationBlock>) {
  const result: Array<AssistantBlockGroup> = []
  let start = -1

  const flushExploreGroup = (end: number) => {
    if (start < 0 || end < start) return

    const groupedBlocks = blocks
      .slice(start, end + 1)
      .filter(isExploreToolBlock)
    const first = groupedBlocks[0]

    if (!first) {
      start = -1
      return
    }

    result.push({
      type: "explore",
      key: `explore:${assistantBlockRenderKey(first, start)}`,
      blocks: groupedBlocks,
    })

    start = -1
  }

  blocks.forEach((block, index) => {
    if (isExploreToolBlock(block)) {
      if (start < 0) {
        start = index
      }
      return
    }

    flushExploreGroup(index - 1)
    result.push({
      type: "block",
      key: assistantBlockRenderKey(block, index),
      block,
    })
  })

  flushExploreGroup(blocks.length - 1)
  return result
}

function sameAssistantBlockGroupDescriptors(
  left: Array<AssistantBlockGroupDescriptor>,
  right: Array<AssistantBlockGroupDescriptor>
) {
  if (left.length !== right.length) return false

  for (let index = 0; index < left.length; index += 1) {
    const leftGroup = left[index]
    const rightGroup = right[index]
    if (!leftGroup || !rightGroup) return false
    if (
      leftGroup.type !== rightGroup.type ||
      leftGroup.key !== rightGroup.key
    ) {
      return false
    }

    if (leftGroup.type === "block" && rightGroup.type === "block") {
      if (leftGroup.blockKey !== rightGroup.blockKey) return false
      continue
    }

    if (leftGroup.type !== "explore" || rightGroup.type !== "explore") {
      return false
    }

    if (leftGroup.blockKeys.length !== rightGroup.blockKeys.length) {
      return false
    }

    for (
      let blockIndex = 0;
      blockIndex < leftGroup.blockKeys.length;
      blockIndex += 1
    ) {
      if (
        leftGroup.blockKeys[blockIndex] !== rightGroup.blockKeys[blockIndex]
      ) {
        return false
      }
    }
  }

  return true
}

function buildAssistantBlockSnapshot(
  blocks: Array<AssistantConversationBlock>,
  previousSnapshot?: AssistantBlockStoreSnapshot
): AssistantBlockStoreSnapshot {
  const blockByKey = new Map<string, AssistantConversationBlock>()
  const fullGroups = groupAssistantBlocks(blocks)

  blocks.forEach((block, index) => {
    blockByKey.set(assistantBlockRenderKey(block, index), block)
  })

  const groups = fullGroups.map((group): AssistantBlockGroupDescriptor => {
    if (group.type === "block") {
      return {
        type: "block",
        key: group.key,
        blockKey: group.key,
      }
    }

    return {
      type: "explore",
      key: group.key,
      blockKeys: group.blocks.map((block) =>
        assistantBlockRenderKey(block, blocks.indexOf(block))
      ),
    }
  })

  return {
    blockByKey,
    groups:
      previousSnapshot &&
      sameAssistantBlockGroupDescriptors(previousSnapshot.groups, groups)
        ? previousSnapshot.groups
        : groups,
    revision: (previousSnapshot?.revision ?? 0) + 1,
  }
}

function createAssistantBlockStore(
  blocks: Array<AssistantConversationBlock>
): AssistantBlockStore {
  let snapshot = buildAssistantBlockSnapshot(blocks)
  const listeners = new Set<() => void>()
  const blockListeners = new Map<string, Set<() => void>>()

  const notifyBlock = (key: string) => {
    const listenersForBlock = blockListeners.get(key)
    if (!listenersForBlock) return
    for (const listener of listenersForBlock) listener()
  }

  return {
    getBlock: (key) => snapshot.blockByKey.get(key),
    getBlocks: (keys) =>
      keys
        .map((key) => snapshot.blockByKey.get(key))
        .filter((block): block is AssistantConversationBlock => Boolean(block)),
    getGroups: () => snapshot.groups,
    setBlocks: (blocks) => {
      const previousSnapshot = snapshot
      const nextSnapshot = buildAssistantBlockSnapshot(blocks, previousSnapshot)
      let blockChanged =
        previousSnapshot.blockByKey.size !== nextSnapshot.blockByKey.size
      const changedKeys = new Set<string>()

      for (const key of previousSnapshot.blockByKey.keys()) {
        if (
          previousSnapshot.blockByKey.get(key) !==
          nextSnapshot.blockByKey.get(key)
        ) {
          changedKeys.add(key)
          blockChanged = true
        }
      }
      for (const key of nextSnapshot.blockByKey.keys()) {
        if (
          previousSnapshot.blockByKey.get(key) !==
          nextSnapshot.blockByKey.get(key)
        ) {
          changedKeys.add(key)
          blockChanged = true
        }
      }

      if (!blockChanged && previousSnapshot.groups === nextSnapshot.groups) {
        return
      }

      snapshot = nextSnapshot
      if (previousSnapshot.groups !== nextSnapshot.groups) {
        for (const listener of listeners) listener()
      }
      for (const key of changedKeys) notifyBlock(key)
    },
    subscribe: (listener) => {
      listeners.add(listener)
      return () => {
        listeners.delete(listener)
      }
    },
    subscribeBlocks: (keys, listener) => {
      const uniqueKeys = [...new Set(keys)]
      for (const key of uniqueKeys) {
        const listenersForBlock =
          blockListeners.get(key) ?? new Set<() => void>()
        listenersForBlock.add(listener)
        blockListeners.set(key, listenersForBlock)
      }

      return () => {
        for (const key of uniqueKeys) {
          const listenersForBlock = blockListeners.get(key)
          if (!listenersForBlock) continue
          listenersForBlock.delete(listener)
          if (listenersForBlock.size === 0) {
            blockListeners.delete(key)
          }
        }
      }
    },
  }
}

function useAssistantBlockGroups(store: AssistantBlockStore) {
  return React.useSyncExternalStore(
    store.subscribe,
    store.getGroups,
    store.getGroups
  )
}

function useAssistantBlock(store: AssistantBlockStore, key: string) {
  return React.useSyncExternalStore(
    React.useCallback(
      (listener) => store.subscribeBlocks([key], listener),
      [key, store]
    ),
    () => store.getBlock(key),
    () => store.getBlock(key)
  )
}

function useAssistantBlocks(store: AssistantBlockStore, keys: Array<string>) {
  const cacheRef = React.useRef<{
    keys: Array<string>
    blocks: Array<AssistantConversationBlock>
  }>({ keys: [], blocks: [] })

  const getSnapshot = () => {
    const blocks = store.getBlocks(keys)
    const cache = cacheRef.current
    if (
      cache.keys.length === keys.length &&
      cache.keys.every((key, index) => key === keys[index]) &&
      cache.blocks.length === blocks.length &&
      cache.blocks.every((block, index) => block === blocks[index])
    ) {
      return cache.blocks
    }

    cacheRef.current = { keys, blocks }
    return blocks
  }

  return React.useSyncExternalStore(
    React.useCallback(
      (listener) => store.subscribeBlocks(keys, listener),
      [keys, store]
    ),
    getSnapshot,
    getSnapshot
  )
}

function compactionTriggerText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "compaction") return "Compaction"
  return block.tokensBefore > 0
    ? `Compaction: Compacted from ${block.tokensBefore.toLocaleString()} tokens`
    : "Compaction"
}

type AnsiStyleState = {
  bold: boolean
  dim: boolean
  italic: boolean
  underline: boolean
  foreground?: string
  background?: string
}

type AnsiTextSegment = {
  text: string
  style?: AnsiStyleState
}

type ParsedAnsiSequence = {
  kind: "sgr" | "control"
  end: number
  params?: string
}

const ANSI_16_COLORS = [
  "#3f3f46",
  "#ef4444",
  "#22c55e",
  "#eab308",
  "#3b82f6",
  "#d946ef",
  "#06b6d4",
  "#e4e4e7",
  "#71717a",
  "#f87171",
  "#4ade80",
  "#facc15",
  "#60a5fa",
  "#e879f9",
  "#22d3ee",
  "#fafafa",
] as const

function defaultAnsiStyle(): AnsiStyleState {
  return {
    bold: false,
    dim: false,
    italic: false,
    underline: false,
  }
}

function cloneAnsiStyle(style: AnsiStyleState): AnsiStyleState | undefined {
  if (
    !style.bold &&
    !style.dim &&
    !style.italic &&
    !style.underline &&
    !style.foreground &&
    !style.background
  ) {
    return undefined
  }

  return { ...style }
}

function ansiStyleKey(style?: AnsiStyleState) {
  if (!style) return ""
  return [
    style.bold ? "1" : "0",
    style.dim ? "1" : "0",
    style.italic ? "1" : "0",
    style.underline ? "1" : "0",
    style.foreground || "",
    style.background || "",
  ].join(";")
}

function pushAnsiTextSegment(
  segments: Array<AnsiTextSegment>,
  text: string,
  style: AnsiStyleState
) {
  if (!text) return

  const nextStyle = cloneAnsiStyle(style)
  const previous = segments[segments.length - 1]

  if (previous && ansiStyleKey(previous.style) === ansiStyleKey(nextStyle)) {
    previous.text += text
    return
  }

  segments.push({ text, style: nextStyle })
}

function parseAnsiSequence(
  text: string,
  index: number
): ParsedAnsiSequence | null {
  const charCode = text.charCodeAt(index)
  const isEsc = charCode === 0x1b
  const isCsi = charCode === 0x9b

  if (!isEsc && !isCsi) return null

  if (isCsi) {
    return parseAnsiCsiSequence(text, index, index + 1)
  }

  const introducer = text[index + 1]

  if (introducer === "[") {
    return parseAnsiCsiSequence(text, index, index + 2)
  }

  if (introducer === "]") {
    const bellEnd = text.indexOf("\u0007", index + 2)
    const stEnd = text.indexOf("\u001b\\", index + 2)
    const candidates = [bellEnd, stEnd].filter((value) => value >= 0)
    const end = candidates.length > 0 ? Math.min(...candidates) : -1

    if (end < 0) {
      return { kind: "control", end: index + 2 }
    }

    return {
      kind: "control",
      end: end === stEnd ? end + 2 : end + 1,
    }
  }

  return { kind: "control", end: Math.min(text.length, index + 2) }
}

function parseAnsiCsiSequence(
  text: string,
  start: number,
  paramsStart: number
): ParsedAnsiSequence | null {
  for (let index = paramsStart; index < text.length; index += 1) {
    const code = text.charCodeAt(index)

    if (code >= 0x40 && code <= 0x7e) {
      const final = text[index]
      return {
        kind: final === "m" ? "sgr" : "control",
        end: index + 1,
        params: text.slice(paramsStart, index),
      }
    }
  }

  return { kind: "control", end: start + 1 }
}

function parseAnsiSgrParams(params = "") {
  if (!params) return [0]

  return params
    .replace(/:/g, ";")
    .split(";")
    .map((param) => {
      if (!param || param.startsWith("?")) return 0
      const value = Number(param)
      return Number.isFinite(value) ? value : 0
    })
}

function ansi256ToCss(value: number | undefined) {
  if (typeof value !== "number") return undefined
  if (value >= 0 && value < 16) return ANSI_16_COLORS[value]

  if (value >= 16 && value <= 231) {
    const offset = value - 16
    const red = Math.floor(offset / 36)
    const green = Math.floor((offset % 36) / 6)
    const blue = offset % 6
    const toChannel = (channel: number) =>
      channel === 0 ? 0 : 55 + channel * 40

    return `rgb(${toChannel(red)} ${toChannel(green)} ${toChannel(blue)})`
  }

  if (value >= 232 && value <= 255) {
    const channel = 8 + (value - 232) * 10
    return `rgb(${channel} ${channel} ${channel})`
  }
}

function readAnsiExtendedColor(codes: Array<number>, index: number) {
  const mode = codes[index + 1]

  if (mode === 5) {
    return {
      color: ansi256ToCss(codes[index + 2]),
      nextIndex: index + 2,
    }
  }

  if (mode === 2) {
    const red = codes[index + 2]
    const green = codes[index + 3]
    const blue = codes[index + 4]

    if ([red, green, blue].every((value) => value >= 0 && value <= 255)) {
      return {
        color: `rgb(${red} ${green} ${blue})`,
        nextIndex: index + 4,
      }
    }
  }

  return { color: undefined, nextIndex: index }
}

function applyAnsiSgrCodes(style: AnsiStyleState, codes: Array<number>) {
  for (let index = 0; index < codes.length; index += 1) {
    const code = codes[index]

    if (code === 0) {
      Object.assign(style, defaultAnsiStyle())
      continue
    }

    if (code === 1) {
      style.bold = true
      continue
    }

    if (code === 2) {
      style.dim = true
      continue
    }

    if (code === 3) {
      style.italic = true
      continue
    }

    if (code === 4) {
      style.underline = true
      continue
    }

    if (code === 22) {
      style.bold = false
      style.dim = false
      continue
    }

    if (code === 23) {
      style.italic = false
      continue
    }

    if (code === 24) {
      style.underline = false
      continue
    }

    if (code === 39) {
      style.foreground = undefined
      continue
    }

    if (code === 49) {
      style.background = undefined
      continue
    }

    if (code >= 30 && code <= 37) {
      style.foreground = ANSI_16_COLORS[code - 30]
      continue
    }

    if (code >= 40 && code <= 47) {
      style.background = ANSI_16_COLORS[code - 40]
      continue
    }

    if (code >= 90 && code <= 97) {
      style.foreground = ANSI_16_COLORS[8 + code - 90]
      continue
    }

    if (code >= 100 && code <= 107) {
      style.background = ANSI_16_COLORS[8 + code - 100]
      continue
    }

    if (code === 38 || code === 48) {
      const extended = readAnsiExtendedColor(codes, index)

      if (extended.color) {
        if (code === 38) {
          style.foreground = extended.color
        } else {
          style.background = extended.color
        }
      }

      index = extended.nextIndex
    }
  }
}

function findNextAnsiSequenceIndex(text: string, start: number) {
  for (let index = start; index < text.length; index += 1) {
    const code = text.charCodeAt(index)

    if (code === 0x1b || code === 0x9b) {
      return index
    }
  }

  return -1
}

function parseAnsiText(text: string): Array<AnsiTextSegment> {
  const segments: Array<AnsiTextSegment> = []
  const style = defaultAnsiStyle()
  let index = 0

  while (index < text.length) {
    const escIndex = findNextAnsiSequenceIndex(text, index)

    if (escIndex < 0) {
      pushAnsiTextSegment(segments, text.slice(index), style)
      break
    }

    pushAnsiTextSegment(segments, text.slice(index, escIndex), style)

    const sequence = parseAnsiSequence(text, escIndex)

    if (!sequence) {
      index = escIndex + 1
      continue
    }

    if (sequence.kind === "sgr") {
      applyAnsiSgrCodes(style, parseAnsiSgrParams(sequence.params))
    }

    index = sequence.end
  }

  return segments
}

function ansiSegmentStyle(
  style?: AnsiStyleState
): React.CSSProperties | undefined {
  if (!style) return undefined

  return {
    color: style.foreground,
    backgroundColor: style.background,
    fontWeight: style.bold ? 700 : undefined,
    fontStyle: style.italic ? "italic" : undefined,
    opacity: style.dim ? 0.72 : undefined,
    textDecorationLine: style.underline ? "underline" : undefined,
  }
}

function AnsiText({ text }: { text: string }) {
  const segments = parseAnsiText(text)

  return (
    <>
      {segments.map((segment, index) => (
        <span key={index} style={ansiSegmentStyle(segment.style)}>
          {segment.text}
        </span>
      ))}
    </>
  )
}

type EditDiffLine = {
  kind: "added" | "removed" | "context" | "omitted"
  marker: string
  lineNumber: string
  content: string
}

function parseEditDiffLine(line: string): EditDiffLine {
  const marker = line.startsWith("+") ? "+" : line.startsWith("-") ? "-" : " "
  const body = line.slice(1)

  if (marker === " " && body.trim() === "...") {
    return {
      kind: "omitted",
      marker: "",
      lineNumber: "",
      content: "...",
    }
  }

  const lineMatch = body.match(/^(\s*\d+)(?: (.*))?$/)
  const kind = marker === "+" ? "added" : marker === "-" ? "removed" : "context"

  if (!lineMatch) {
    return {
      kind,
      marker,
      lineNumber: "",
      content: body,
    }
  }

  return {
    kind,
    marker,
    lineNumber: lineMatch[1].trim(),
    content: lineMatch[2] ?? "",
  }
}

function parseEditDiff(diff: string) {
  const lines = diff.split("\n").map((line) => parseEditDiffLine(line))
  const lineNumberWidth = Math.max(
    1,
    ...lines.map((line) => line.lineNumber.length)
  )

  return { lines, lineNumberWidth }
}

function getEditDiffStats(diff: string) {
  const stats = { additions: 0, removals: 0 }

  if (!diff) return stats

  for (const line of diff.split("\n")) {
    if (line.startsWith("+")) stats.additions += 1
    if (line.startsWith("-")) stats.removals += 1
  }

  return stats
}

function editDiffLineClassName(kind: EditDiffLine["kind"]) {
  switch (kind) {
    case "added":
      return "bg-success/10"
    case "removed":
      return "bg-destructive/10"
    default:
      return ""
  }
}

function editDiffMarkerClassName(kind: EditDiffLine["kind"]) {
  switch (kind) {
    case "added":
      return "text-success"
    case "removed":
      return "text-destructive"
    default:
      return "text-muted-foreground"
  }
}

function EditDiffStats({ diff }: { diff: string }) {
  const stats = getEditDiffStats(diff)

  if (!stats.additions && !stats.removals) return null

  return (
    <span
      className="flex shrink-0 items-center gap-2 font-mono text-sm"
      aria-label={`${stats.additions} lines added, ${stats.removals} lines removed`}
    >
      <span className="text-success">+{stats.additions}</span>
      <span className="text-destructive">−{stats.removals}</span>
    </span>
  )
}

function EditDiffBlock({
  diff,
  language,
}: {
  diff: string
  language?: string
}) {
  const parsed = parseEditDiff(diff)
  const code = parsed.lines
    .map((line) => (line.kind === "omitted" ? "" : line.content))
    .join("\n")
  const [highlighted, setHighlighted] =
    React.useState<HighlightResponse | null>(null)

  React.useEffect(() => {
    let cancelled = false

    if (!language || !code.trim()) {
      setHighlighted(null)
      return
    }

    setHighlighted(null)
    void getHighlightedCode(code, language)
      .then((payload) => {
        if (!cancelled) {
          setHighlighted(payload)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setHighlighted({ ok: true, unavailable: true })
        }
      })

    return () => {
      cancelled = true
    }
  }, [code, language])

  const renderedLanguage =
    highlighted && "language" in highlighted && highlighted.language
      ? highlighted.language
      : language
  const highlightedHtml = hasHighlightHtml(highlighted)
    ? highlighted.html
    : null
  const highlightedLines = highlightedHtml ? highlightedHtml.split("\n") : []

  return (
    <div className="overflow-hidden rounded-md border bg-muted/20 py-1 font-mono text-xs leading-5">
      <div className="w-max min-w-full">
        {parsed.lines.map((line, index) => {
          const highlightedLine = highlightedLines[index]

          return (
            <div
              key={index}
              className={cn(
                "flex w-max min-w-full whitespace-pre",
                editDiffLineClassName(line.kind)
              )}
            >
              <span
                className={cn(
                  "w-4 shrink-0 pr-1 text-right select-none",
                  editDiffMarkerClassName(line.kind)
                )}
              >
                {line.marker}
              </span>
              <span
                className="shrink-0 pr-3 text-right text-muted-foreground select-none"
                style={{ width: `${parsed.lineNumberWidth}ch` }}
              >
                {line.lineNumber}
              </span>
              <span
                className={cn(
                  "pr-4 pl-3",
                  line.kind === "omitted" && "text-muted-foreground"
                )}
              >
                {highlightedLine && line.kind !== "omitted" ? (
                  <code
                    className={cn(
                      renderedLanguage && `language-${renderedLanguage}`
                    )}
                    // biome-ignore lint/security/noDangerouslySetInnerHtml: syntax highlighting HTML is generated by sugar-high
                    dangerouslySetInnerHTML={{ __html: highlightedLine }}
                  />
                ) : (
                  <code>{line.content}</code>
                )}
              </span>
            </div>
          )
        })}
      </div>
    </div>
  )
}

function PlainToolOutput({ text }: { text: string }) {
  return (
    <pre className="overflow-x-auto font-mono text-xs leading-5 break-words whitespace-pre-wrap">
      {text}
    </pre>
  )
}

const ToolBlockSection = React.memo(function ToolBlockSection({
  label,
  text,
}: {
  label: string
  text: string
}) {
  return (
    <section className="space-y-1.5">
      <div className="text-[11px] font-medium tracking-wide text-muted-foreground uppercase">
        {label}
      </div>
      <PlainToolOutput text={text} />
    </section>
  )
})

function editToolOutputWithoutSuccessMessage(output: string) {
  return output
    .split("\n")
    .filter(
      (line) => !/^Successfully replaced \d+ block\(s\) in .+\.$/.test(line)
    )
    .join("\n")
    .trimEnd()
}

function EditToolOutput({
  block,
}: {
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
    type: "tool"
  }
}) {
  const diff = toolDiffText(block)
  const output = editToolOutputWithoutSuccessMessage(block.output.trimEnd())
  const extraOutput = output && output !== diff ? output : ""
  const fallbackOutput = editToolOutputWithoutSuccessMessage(
    toolOutputText(block)
  )
  const language = codeLanguageFromPath(toolFilePath(block))

  if (!diff) {
    return <PlainToolOutput text={fallbackOutput || "No output available."} />
  }

  return (
    <div className="space-y-3">
      <EditDiffBlock diff={diff} language={language} />
      {extraOutput ? <PlainToolOutput text={extraOutput} /> : null}
    </div>
  )
}

const ToolBlockCard = React.memo(function ToolBlockCard({
  block,
}: {
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
    type: "tool"
  }
}) {
  const callText = toolCallText(block)
  const outputText = toolOutputText(block)
  const editDiff = block.name === "edit" ? toolDiffText(block) : ""
  const shellBodyText =
    block.name === "bash"
      ? [callText, block.output.trimEnd()].filter(Boolean).join("\n\n") ||
        callText ||
        outputText
      : ""

  return (
    <Accordion
      className={cn(
        "rounded-xl border text-sm",
        block.running && "border-amber-500/30 bg-amber-500/5",
        block.isError && "border-destructive/30 bg-destructive/5",
        !block.running && !block.isError && "bg-muted/20"
      )}
    >
      <AccordionItem value="tool" className="border-0">
        <AccordionTrigger
          data-conversation-tool-accordion-trigger="true"
          className="min-w-0 items-center gap-3 overflow-hidden px-3 py-2.5 hover:no-underline"
        >
          <span className="grid max-w-full min-w-0 flex-1 grid-cols-[auto_minmax(0,1fr)] items-center gap-3 overflow-hidden">
            <span className="truncate font-medium whitespace-nowrap text-foreground">
              {toolDisplayName(block.name)}
            </span>
            <span className="truncate text-muted-foreground">
              {toolSummary(block)}
            </span>
          </span>
          {block.name === "edit" ? <EditDiffStats diff={editDiff} /> : null}
        </AccordionTrigger>

        <AccordionContent className="px-3 pb-3">
          <div className="border-t pt-3">
            <div className="max-h-96 overflow-auto rounded-lg border bg-background/80 p-3">
              {block.name === "bash" ? (
                <pre className="overflow-x-auto font-mono text-xs leading-5 break-words whitespace-pre-wrap">
                  <AnsiText text={shellBodyText} />
                </pre>
              ) : block.name === "edit" ? (
                <EditToolOutput block={block} />
              ) : (
                <div className="space-y-4">
                  {callText ? (
                    <ToolBlockSection label="Call" text={callText} />
                  ) : null}
                  <ToolBlockSection
                    label={block.running ? "Output (streaming)" : "Output"}
                    text={outputText}
                  />
                </div>
              )}
            </div>
          </div>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
})

const ExploreToolGroupCard = React.memo(function ExploreToolGroupCard({
  blocks,
}: {
  blocks: Array<
    Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
      type: "tool"
    }
  >
}) {
  const summary = exploreGroupSummary(blocks)
  const statusLabel = exploreGroupStatusLabel()
  const hasRunning = blocks.some((block) => block.running)
  const hasError = blocks.some((block) => block.isError)

  return (
    <Accordion
      className={cn(
        "rounded-xl border text-sm",
        hasRunning && "border-amber-500/30 bg-amber-500/5",
        !hasRunning && hasError && "border-destructive/30 bg-destructive/5",
        !hasRunning && !hasError && "bg-muted/20"
      )}
    >
      <AccordionItem value="explore" className="border-0">
        <AccordionTrigger
          data-conversation-tool-accordion-trigger="true"
          className="min-w-0 items-center gap-3 overflow-hidden px-3 py-2.5 hover:no-underline"
        >
          <span className="grid max-w-full min-w-0 flex-1 grid-cols-[auto_minmax(0,1fr)] items-center gap-3 overflow-hidden">
            <span className="truncate font-medium whitespace-nowrap text-foreground">
              {statusLabel}
            </span>
            <span className="truncate text-muted-foreground">{summary}</span>
          </span>
        </AccordionTrigger>

        <AccordionContent className="px-3 pb-3">
          <div className="border-t pt-3">
            <div className="max-h-96 overflow-auto rounded-lg border bg-background/80 p-3">
              <div className="space-y-3">
                {blocks.map((block, index) => {
                  const line = exploreToolLine(block)
                  const lineText = line.details || toolSummary(block)

                  return (
                    <div
                      key={
                        block.blockKey ||
                        block.callId ||
                        `${block.name || "tool"}:${index}`
                      }
                      className="grid grid-cols-[auto_minmax(0,1fr)] items-baseline gap-3 text-sm"
                    >
                      <span className="truncate font-medium whitespace-nowrap text-foreground">
                        {line.label}
                      </span>
                      <span
                        className={cn(
                          "truncate text-muted-foreground",
                          block.isError && "text-destructive"
                        )}
                        title={lineText}
                      >
                        {lineText}
                      </span>
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
})

const CompactionBlockCard = React.memo(function CompactionBlockCard({
  block,
}: {
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
    type: "compaction"
  }
}) {
  return (
    <details className="rounded-xl border bg-muted/20 px-3 py-2">
      <summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-medium text-foreground">
        <ChevronRightIcon className="size-4 text-muted-foreground" />
        <span>{compactionTriggerText(block)}</span>
      </summary>
      <div className="mt-3 border-t pt-3">
        {block.summary.trim() ? (
          <MarkdownBlock text={block.summary} />
        ) : (
          <div className="text-sm text-muted-foreground">
            No compaction summary available.
          </div>
        )}
      </div>
    </details>
  )
})

export function MessagesWorkingIndicator({
  state,
}: {
  state: {
    label: string
    summary?: string
    done?: boolean
  }
}) {
  const visibleLabel = state.done ? "Done" : state.label

  return (
    <div
      role="status"
      aria-live="polite"
      className={cn(
        "flex w-full items-start gap-3 rounded-xl px-1 py-1 text-sm",
        state.done ? "text-muted-foreground" : "text-muted-foreground"
      )}
    >
      <span className="mt-0.5 inline-flex items-center justify-center">
        {state.done ? (
          <CheckIcon className="size-4 text-emerald-600" />
        ) : (
          <Spinner />
        )}
      </span>
      <div className="min-w-0 flex-1">
        <div className="font-medium text-foreground">{visibleLabel}</div>
        {state.summary ? (
          <div className="truncate text-muted-foreground">{state.summary}</div>
        ) : null}
      </div>
    </div>
  )
}

export const UserMessageCard = React.memo(function UserMessageCard({
  item,
}: {
  item: Extract<ConversationItem, { kind: "user" }>
}) {
  const labelText = userMessageLabel(item)

  return (
    <div className="w-full rounded-xl border bg-primary/6 px-4 py-3">
      {labelText ? (
        <div className="mb-2 flex items-center gap-2">
          <Badge variant="outline">{labelText}</Badge>
        </div>
      ) : null}
      {item.text ? (
        <div className="text-sm break-words whitespace-pre-wrap text-foreground">
          {item.text}
        </div>
      ) : (
        <div className="text-sm text-muted-foreground">Image prompt</div>
      )}
      {item.images.length > 0 ? (
        <div className="mt-3 flex flex-wrap gap-3">
          {item.images.map((image) => (
            <img
              key={promptImageKey(image)}
              src={image.previewUrl}
              alt="Prompt upload"
              className="h-28 rounded-lg border object-cover"
            />
          ))}
        </div>
      ) : null}
    </div>
  )
})

function assistantBlockIsVisible({
  block,
  hideThinking,
  hideToolBlocks,
}: {
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
  hideThinking: boolean
  hideToolBlocks: boolean
}) {
  switch (block.type) {
    case "text":
      return Boolean(block.text.trim())
    case "compaction":
      return true
    case "thinking":
      return !hideThinking
    case "tool":
      return !hideToolBlocks
    default:
      return false
  }
}

export function assistantMessageHasVisibleBlocks({
  item,
  hideThinking,
  hideToolBlocks,
}: {
  item: Extract<ConversationItem, { kind: "assistant" }>
  hideThinking: boolean
  hideToolBlocks: boolean
}) {
  return item.blocks.some((block) =>
    assistantBlockIsVisible({ block, hideThinking, hideToolBlocks })
  )
}

const AssistantBlockGroupView = React.memo(function AssistantBlockGroupView({
  descriptor,
  store,
  streaming,
}: {
  descriptor: AssistantBlockGroupDescriptor
  store: AssistantBlockStore
  streaming: boolean
}) {
  if (descriptor.type === "explore") {
    return (
      <AssistantExploreBlockGroupView
        blockKeys={descriptor.blockKeys}
        store={store}
      />
    )
  }

  return (
    <AssistantSingleBlockGroupView
      blockKey={descriptor.blockKey}
      store={store}
      streaming={streaming}
    />
  )
})

function AssistantExploreBlockGroupView({
  blockKeys,
  store,
}: {
  blockKeys: Array<string>
  store: AssistantBlockStore
}) {
  const blocks = useAssistantBlocks(store, blockKeys).filter(isExploreToolBlock)
  if (blocks.length === 0) return null

  return <ExploreToolGroupCard blocks={blocks} />
}

function AssistantSingleBlockGroupView({
  blockKey,
  store,
  streaming,
}: {
  blockKey: string
  store: AssistantBlockStore
  streaming: boolean
}) {
  const block = useAssistantBlock(store, blockKey)
  if (!block) return null

  switch (block.type) {
    case "text":
      return <MarkdownBlock text={block.text} streaming={streaming} />
    case "thinking":
      return (
        <section className="border-l-2 border-amber-500/45 pl-4 text-sm text-muted-foreground">
          <MarkdownBlock text={block.text} streaming={streaming} />
        </section>
      )
    case "tool":
      return <ToolBlockCard block={block} />
    case "compaction":
      return <CompactionBlockCard block={block} />
    default:
      return null
  }
}

function AssistantBlockGroupsView({
  store,
  streaming,
}: {
  store: AssistantBlockStore
  streaming: boolean
}) {
  const renderedBlocks = useAssistantBlockGroups(store)

  return (
    <>
      {renderedBlocks.map((descriptor) => (
        <AssistantBlockGroupView
          key={descriptor.key}
          descriptor={descriptor}
          store={store}
          streaming={streaming}
        />
      ))}
    </>
  )
}

export const AssistantMessagesCard = React.memo(function AssistantMessagesCard({
  items,
  hideThinking,
  hideToolBlocks,
}: {
  items: Array<Extract<ConversationItem, { kind: "assistant" }>>
  hideThinking: boolean
  hideToolBlocks: boolean
}) {
  const streaming = items.some((item) => item.streaming)
  const blocks = items.flatMap((item) =>
    item.blocks.filter((block) =>
      assistantBlockIsVisible({ block, hideThinking, hideToolBlocks })
    )
  )

  if (blocks.length === 0) {
    return null
  }

  const assistantBlockStoreRef = React.useRef<AssistantBlockStore | null>(null)
  if (!assistantBlockStoreRef.current) {
    assistantBlockStoreRef.current = createAssistantBlockStore(blocks)
  }
  const assistantBlockStore = assistantBlockStoreRef.current

  React.useLayoutEffect(() => {
    assistantBlockStore.setBlocks(blocks)
  }, [assistantBlockStore, blocks])

  return (
    <div className="flex flex-col gap-4">
      <AssistantBlockGroupsView
        store={assistantBlockStore}
        streaming={streaming}
      />
    </div>
  )
})

export const AssistantMessageCard = React.memo(function AssistantMessageCard({
  item,
  hideThinking,
  hideToolBlocks,
}: {
  item: Extract<ConversationItem, { kind: "assistant" }>
  hideThinking: boolean
  hideToolBlocks: boolean
}) {
  return (
    <AssistantMessagesCard
      items={[item]}
      hideThinking={hideThinking}
      hideToolBlocks={hideToolBlocks}
    />
  )
})
