"use client"

/* biome-ignore-all lint/security/noDangerouslySetInnerHtml: syntax highlighting HTML is generated by sugar-high */

import * as React from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { CheckIcon, ChevronRightIcon, CopyIcon } from "lucide-react"

import type { ConversationItem, PromptImage } from "@/lib/pi-web"
import type { HighlightResponse } from "@/lib/pi-web-api"

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

const highlightCache = new Map<
  string,
  Promise<HighlightResponse> | HighlightResponse
>()

const MemoizedReactMarkdown = React.memo(ReactMarkdown)
const MARKDOWN_REMARK_PLUGINS = [remarkGfm]
const MARKDOWN_COMPONENTS = {
  code({ className, children, ...props }) {
    return (
      <code
        className={cn(
          "rounded bg-muted px-1 py-0.5 font-mono text-[0.92em] text-[#f19232] before:content-none after:content-none",
          className
        )}
        {...props}
      >
        {children}
      </code>
    )
  },
  pre({ children }) {
    const codeElement = getCodeBlockChild(children)

    if (!codeElement) {
      return <pre>{children}</pre>
    }

    const code = markdownNodeText(codeElement.props.children).replace(/\n$/, "")
    const language = parseCodeLanguage(codeElement.props.className)

    return <CodeBlock code={code} language={language} />
  },
} satisfies NonNullable<
  React.ComponentProps<typeof ReactMarkdown>["components"]
>

function parseCodeLanguage(className?: string) {
  const match = className?.match(/language-([A-Za-z0-9_+#.-]+)/)
  return match?.[1]
}

function markdownNodeText(node: React.ReactNode): string {
  if (typeof node === "string" || typeof node === "number") {
    return String(node)
  }

  if (Array.isArray(node)) {
    return node.map((child) => markdownNodeText(child)).join("")
  }

  if (React.isValidElement<{ children?: React.ReactNode }>(node)) {
    return markdownNodeText(node.props.children)
  }

  return ""
}

async function getHighlightedCode(code: string, language?: string) {
  if (!language) {
    return {
      ok: true,
      skipped: true,
    } satisfies HighlightResponse
  }

  const cacheKey = `${language}\u0000${code}`
  const cached = highlightCache.get(cacheKey)
  if (cached) {
    return await cached
  }

  const promise = fetch("/api/highlight", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ code, language }),
  }).then(async (response) => {
    const payload = (await response.json()) as HighlightResponse
    return payload
  })

  highlightCache.set(cacheKey, promise)
  const payload = await promise
  highlightCache.set(cacheKey, payload)
  return payload
}

const CodeBlock = React.memo(function CodeBlock({
  code,
  language,
}: {
  code: string
  language?: string
}) {
  const [highlighted, setHighlighted] =
    React.useState<HighlightResponse | null>(null)
  const [copyState, setCopyState] = React.useState<"idle" | "copied" | "error">(
    "idle"
  )

  React.useEffect(() => {
    let cancelled = false

    if (!language) {
      setHighlighted(null)
      return
    }

    setHighlighted(null)
    void getHighlightedCode(code, language)
      .then((payload) => {
        if (!cancelled) {
          setHighlighted(payload)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setHighlighted({ ok: true, unavailable: true })
        }
      })

    return () => {
      cancelled = true
    }
  }, [code, language])

  const renderedLanguage =
    highlighted && "language" in highlighted && highlighted.language
      ? highlighted.language
      : language

  const copyCode = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopyState("copied")
      window.setTimeout(() => setCopyState("idle"), 1400)
    } catch {
      setCopyState("error")
      window.setTimeout(() => setCopyState("idle"), 1400)
    }
  }

  const highlightedHtml = hasHighlightHtml(highlighted)
    ? highlighted.html
    : null

  const highlightedMarkup = { __html: highlightedHtml || "" }

  const highlightedContent = highlightedHtml ? (
    <code
      className={cn(renderedLanguage && `language-${renderedLanguage}`)}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: syntax highlighting HTML is generated by sugar-high
      dangerouslySetInnerHTML={highlightedMarkup}
    />
  ) : null

  return (
    <div className="not-prose overflow-hidden rounded-xl border bg-muted/40">
      <div className="flex items-center justify-between gap-3 border-b bg-background/80 px-3 py-2 text-xs text-muted-foreground">
        <div className="truncate font-medium tracking-wide uppercase">
          {renderedLanguage || "code"}
        </div>
        <Button variant="ghost" size="xs" onClick={copyCode}>
          {copyState === "copied" ? (
            <CheckIcon data-icon="inline-start" />
          ) : (
            <CopyIcon data-icon="inline-start" />
          )}
          {copyState === "copied"
            ? "Copied"
            : copyState === "error"
              ? "Retry"
              : "Copy"}
        </Button>
      </div>
      <pre className="overflow-x-auto bg-transparent px-4 py-3 text-[13px] leading-6 text-foreground">
        {highlightedContent || <code>{code}</code>}
      </pre>
    </div>
  )
})

function isHighlightSkipped(payload: HighlightResponse) {
  return (
    "skipped" in payload ||
    "unsupported" in payload ||
    "unavailable" in payload ||
    ("ok" in payload && payload.ok === false)
  )
}

function isHighlightUnavailable(payload: HighlightResponse) {
  return "unavailable" in payload || ("ok" in payload && payload.ok === false)
}

function hasHighlightHtml(
  payload: HighlightResponse | null
): payload is Exclude<
  HighlightResponse,
  { ok: false; error: string; routePath?: string }
> & { html: string } {
  return Boolean(
    payload && !isHighlightSkipped(payload) && !isHighlightUnavailable(payload)
  )
}

function getCodeBlockChild(children: React.ReactNode) {
  const child = React.Children.toArray(children).find((node) =>
    React.isValidElement<{ children?: React.ReactNode; className?: string }>(
      node
    )
  )

  if (
    !React.isValidElement<{
      children?: React.ReactNode
      className?: string
    }>(child)
  ) {
    return null
  }

  return child
}

const MarkdownBlock = React.memo(function MarkdownBlock({
  text,
}: {
  text: string
}) {
  return (
    <div className="prose prose-sm max-w-none wrap-break-word dark:prose-invert prose-headings:font-semibold prose-p:my-2 prose-pre:m-0 prose-ol:my-2 prose-ul:my-2">
      <MemoizedReactMarkdown
        remarkPlugins={MARKDOWN_REMARK_PLUGINS}
        components={MARKDOWN_COMPONENTS}
      >
        {text}
      </MemoizedReactMarkdown>
    </div>
  )
})

export function promptImageKey(
  image: Pick<PromptImage, "previewUrl" | "data">
) {
  return `${image.previewUrl}:${image.data.slice(0, 24)}`
}

function toolArgsKey(args: unknown) {
  if (typeof args === "string") return args
  if (args == null) return ""

  try {
    return JSON.stringify(args)
  } catch {
    return ""
  }
}

function assistantBlockKey(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  switch (block.type) {
    case "text":
      return `text:${block.text}`
    case "thinking":
      return `thinking:${block.text}`
    case "tool":
      return `tool:${block.callId || block.name || "tool"}:${toolArgsKey(block.args)}`
    case "compaction":
      return `compaction:${block.tokensBefore}:${block.summary}`
    default:
      return "block"
  }
}

export function conversationItemSignature(item: ConversationItem) {
  if (item.kind === "user") {
    return `user:${item.pendingId || ""}:${item.text}:${item.images
      .map((image) => promptImageKey(image))
      .join(",")}:${item.streamingBehavior || ""}:${item.queued ? "1" : "0"}`
  }

  return `assistant:${item.blocks.map((block) => assistantBlockKey(block)).join("|")}:${
    item.streaming ? "1" : "0"
  }`
}

function userMessageLabel(item: Extract<ConversationItem, { kind: "user" }>) {
  if (item.streamingBehavior === "steer") return "Steer"
  if (item.queued || item.streamingBehavior === "followUp") return "Queue"
  return ""
}

function toolDisplayName(name?: string) {
  switch (name) {
    case "bash":
      return "Shell"
    case "read":
      return "Read"
    case "write":
      return "Write"
    case "edit":
      return "Edit"
    case "grep":
      return "Search"
    case "find":
      return "Find"
    case "ls":
      return "List"
    default:
      return name || "Tool"
  }
}

function normalizeToolArgs(args: unknown) {
  if (!args) return undefined
  if (typeof args === "object") {
    return args as Record<string, unknown>
  }
  if (typeof args !== "string") return undefined

  try {
    const parsed = JSON.parse(args)
    return parsed && typeof parsed === "object"
      ? (parsed as Record<string, unknown>)
      : undefined
  } catch {
    return undefined
  }
}

function getToolArgText(
  args: Record<string, unknown> | undefined,
  key: string
) {
  const value = args?.[key]
  return typeof value === "string" && value.trim() ? value.trim() : ""
}

function toolCommandPreview(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  if (typeof block.args === "string" && block.args.trim()) {
    return block.args.trim()
  }

  const args = normalizeToolArgs(block.args)
  return (
    getToolArgText(args, "description") ||
    getToolArgText(args, "command") ||
    getToolArgText(args, "path") ||
    getToolArgText(args, "filePath")
  )
}

function toolReadLocation(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  const args = normalizeToolArgs(block.args)
  const filePath =
    getToolArgText(args, "path") || getToolArgText(args, "filePath")
  const offset = args?.offset
  const limit = args?.limit

  if (typeof offset === "number" && typeof limit === "number" && limit > 0) {
    return `${filePath}:${offset}-${offset + limit - 1}`
  }
  if (typeof offset === "number") {
    return `${filePath}:${offset}`
  }
  if (typeof limit === "number" && limit > 0) {
    return `${filePath} limit=${limit}`.trim()
  }
  return filePath
}

function collapseToolPreview(text: string) {
  return text.replace(/\s+/g, " ").trim()
}

function toolSummary(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""
  const preview =
    block.name === "read" ? toolReadLocation(block) : toolCommandPreview(block)
  if (preview) return collapseToolPreview(preview)
  if (block.running) return "Running"
  if (block.isError) return "Failed"
  return "Done"
}

function formatToolArgString(value: string) {
  const trimmed = value.trim()
  if (!trimmed) return ""

  try {
    const parsed = JSON.parse(trimmed)
    if (parsed && typeof parsed === "object") {
      return JSON.stringify(parsed, null, 2)
    }
  } catch {
    // fall through to the raw string below
  }

  return trimmed
}

function toolCallText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  if (typeof block.args === "string") {
    const text = formatToolArgString(block.args)
    return block.name === "bash" && text ? `$ ${text}` : text
  }

  if (block.args == null) return ""

  try {
    return JSON.stringify(block.args, null, 2) || ""
  } catch {
    return ""
  }
}

function toolDiffText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool" || block.name !== "edit") return ""

  return block.details &&
    typeof block.details === "object" &&
    "diff" in block.details &&
    typeof block.details.diff === "string"
    ? block.details.diff.trimEnd()
    : ""
}

function toolOutputText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "tool") return ""

  const parts: Array<string> = []
  const diff = toolDiffText(block)
  const output = block.output.trimEnd()

  if (diff) {
    parts.push(diff)
  }

  if (output && (!diff || output !== diff)) {
    parts.push(output)
  }

  if (parts.length > 0) {
    return parts.join("\n\n")
  }

  if (block.running) return "Running…"
  if (block.isError) return "Tool failed with no output."
  return "No output available."
}

function compactionTriggerText(
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number]
) {
  if (block.type !== "compaction") return "Compaction"
  return block.tokensBefore > 0
    ? `Compaction: Compacted from ${block.tokensBefore.toLocaleString()} tokens`
    : "Compaction"
}

const ToolBlockSection = React.memo(function ToolBlockSection({
  label,
  text,
}: {
  label: string
  text: string
}) {
  return (
    <section className="space-y-1.5">
      <div className="text-[11px] font-medium tracking-wide text-muted-foreground uppercase">
        {label}
      </div>
      <pre className="overflow-x-auto font-mono text-xs leading-5 break-words whitespace-pre-wrap">
        {text}
      </pre>
    </section>
  )
})

const ToolBlockCard = React.memo(function ToolBlockCard({
  block,
}: {
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
    type: "tool"
  }
}) {
  const callText = toolCallText(block)
  const outputText = toolOutputText(block)

  return (
    <Accordion
      className={cn(
        "rounded-xl border text-sm",
        block.running && "border-amber-500/30 bg-amber-500/5",
        block.isError && "border-destructive/30 bg-destructive/5",
        !block.running && !block.isError && "bg-muted/20"
      )}
    >
      <AccordionItem value="tool" className="border-0">
        <AccordionTrigger className="min-w-0 items-center gap-3 overflow-hidden px-3 py-2.5 hover:no-underline">
          <span className="grid max-w-full min-w-0 flex-1 grid-cols-[auto_minmax(0,1fr)] items-center gap-3 overflow-hidden">
            <span className="truncate font-medium whitespace-nowrap text-foreground">
              {toolDisplayName(block.name)}
            </span>
            <span className="truncate text-muted-foreground">
              {toolSummary(block)}
            </span>
          </span>
        </AccordionTrigger>

        <AccordionContent className="px-3 pb-3">
          <div className="border-t pt-3">
            <div className="max-h-96 overflow-auto rounded-lg border bg-background/80 p-3">
              <div className="space-y-4">
                {callText ? (
                  <ToolBlockSection label="Call" text={callText} />
                ) : null}
                <ToolBlockSection
                  label={block.running ? "Output (streaming)" : "Output"}
                  text={outputText}
                />
              </div>
            </div>
          </div>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
})

const CompactionBlockCard = React.memo(function CompactionBlockCard({
  block,
}: {
  block: Extract<ConversationItem, { kind: "assistant" }>["blocks"][number] & {
    type: "compaction"
  }
}) {
  return (
    <details className="rounded-xl border bg-muted/20 px-3 py-2">
      <summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-medium text-foreground">
        <ChevronRightIcon className="size-4 text-muted-foreground" />
        <span>{compactionTriggerText(block)}</span>
      </summary>
      <div className="mt-3 border-t pt-3">
        {block.summary.trim() ? (
          <MarkdownBlock text={block.summary} />
        ) : (
          <div className="text-sm text-muted-foreground">
            No compaction summary available.
          </div>
        )}
      </div>
    </details>
  )
})

export function MessagesWorkingIndicator({
  state,
}: {
  state: {
    label: string
    summary?: string
    done?: boolean
  }
}) {
  const visibleLabel = state.done ? "Done" : state.label

  return (
    <div
      role="status"
      aria-live="polite"
      className={cn(
        "flex w-full items-start gap-3 rounded-xl px-1 py-1 text-sm",
        state.done ? "text-muted-foreground" : "text-muted-foreground"
      )}
    >
      <span className="mt-0.5 inline-flex items-center justify-center">
        {state.done ? (
          <CheckIcon className="size-4 text-emerald-600" />
        ) : (
          <Spinner />
        )}
      </span>
      <div className="min-w-0 flex-1">
        <div className="font-medium text-foreground">{visibleLabel}</div>
        {state.summary ? (
          <div className="truncate text-muted-foreground">{state.summary}</div>
        ) : null}
      </div>
    </div>
  )
}

export const UserMessageCard = React.memo(function UserMessageCard({
  item,
}: {
  item: Extract<ConversationItem, { kind: "user" }>
}) {
  const labelText = userMessageLabel(item)

  return (
    <div className="w-full rounded-xl border bg-primary/6 px-4 py-3">
      {labelText ? (
        <div className="mb-2 flex items-center gap-2">
          <Badge variant="outline">{labelText}</Badge>
        </div>
      ) : null}
      {item.text ? (
        <div className="text-sm break-words whitespace-pre-wrap text-foreground">
          {item.text}
        </div>
      ) : (
        <div className="text-sm text-muted-foreground">Image prompt</div>
      )}
      {item.images.length > 0 ? (
        <div className="mt-3 flex flex-wrap gap-3">
          {item.images.map((image) => (
            <img
              key={promptImageKey(image)}
              src={image.previewUrl}
              alt="Prompt upload"
              className="h-28 rounded-lg border object-cover"
            />
          ))}
        </div>
      ) : null}
    </div>
  )
})

export function assistantMessageHasVisibleBlocks({
  item,
  hideThinking,
  hideToolBlocks,
}: {
  item: Extract<ConversationItem, { kind: "assistant" }>
  hideThinking: boolean
  hideToolBlocks: boolean
}) {
  return item.blocks.some((block) => {
    switch (block.type) {
      case "text":
      case "compaction":
        return true
      case "thinking":
        return !hideThinking
      case "tool":
        return !hideToolBlocks
      default:
        return false
    }
  })
}

export const AssistantMessageCard = React.memo(function AssistantMessageCard({
  item,
  hideThinking,
  hideToolBlocks,
}: {
  item: Extract<ConversationItem, { kind: "assistant" }>
  hideThinking: boolean
  hideToolBlocks: boolean
}) {
  const renderedBlocks = (() => {
    const counts = new Map<string, number>()
    return item.blocks.flatMap((block) => {
      const fallbackKey = assistantBlockKey(block)
      const count = (counts.get(fallbackKey) ?? 0) + 1
      counts.set(fallbackKey, count)
      const key = block.blockKey || `${fallbackKey}:${count}`

      switch (block.type) {
        case "text":
          return <MarkdownBlock key={key} text={block.text} />
        case "thinking":
          if (hideThinking) {
            return []
          }

          return (
            <section
              key={key}
              className="border-l-2 border-amber-500/45 pl-4 text-sm text-muted-foreground"
            >
              <MarkdownBlock text={block.text} />
            </section>
          )
        case "tool":
          if (hideToolBlocks) {
            return []
          }

          return <ToolBlockCard key={key} block={block} />
        case "compaction":
          return <CompactionBlockCard key={key} block={block} />
        default:
          return []
      }
    })
  })()

  if (
    !assistantMessageHasVisibleBlocks({ item, hideThinking, hideToolBlocks })
  ) {
    return null
  }

  return <div className="flex flex-col gap-4">{renderedBlocks}</div>
})
