export const SHIKI_BUNDLED_THEME_PAIR_DEFINITIONS = [
  {
    id: "shiki-pair-ayu",
    label: "Ayu",
    description: "Use Ayu Light in light mode and Ayu Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "ayu-light",
      "ayu-dark",
      "Ayu",
      "Ayu Light",
      "Ayu Dark",
      "ayu",
    ],
    classes: {
      light: "shiki-theme-ayu-light",
      dark: "shiki-theme-ayu-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-ayu-mirage",
    label: "Ayu Mirage",
    description: "Use Ayu Light in light mode and Ayu Mirage in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "ayu-light",
      "ayu-mirage",
      "Ayu Mirage",
      "Ayu Light",
      "ayu",
      "mirage",
    ],
    classes: {
      light: "shiki-theme-ayu-light",
      dark: "shiki-theme-ayu-mirage",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-catppuccin-frappe",
    label: "Catppuccin Frappé",
    description:
      "Use Catppuccin Latte in light mode and Catppuccin Frappé in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "catppuccin-latte",
      "catppuccin-frappe",
      "Catppuccin Frappé",
      "Catppuccin Latte",
      "catppuccin",
      "frappe",
      "frappé",
      "latte",
    ],
    classes: {
      light: "shiki-theme-catppuccin-latte",
      dark: "shiki-theme-catppuccin-frappe",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    description:
      "Use Catppuccin Latte in light mode and Catppuccin Macchiato in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "Catppuccin Macchiato",
      "Catppuccin Latte",
      "catppuccin",
      "macchiato",
      "latte",
    ],
    classes: {
      light: "shiki-theme-catppuccin-latte",
      dark: "shiki-theme-catppuccin-macchiato",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-catppuccin-mocha",
    label: "Catppuccin Mocha",
    description:
      "Use Catppuccin Latte in light mode and Catppuccin Mocha in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "catppuccin-latte",
      "catppuccin-mocha",
      "Catppuccin Mocha",
      "Catppuccin Latte",
      "catppuccin",
      "mocha",
      "latte",
    ],
    classes: {
      light: "shiki-theme-catppuccin-latte",
      dark: "shiki-theme-catppuccin-mocha",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-everforest",
    label: "Everforest",
    description:
      "Use Everforest Light in light mode and Everforest Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "everforest-light",
      "everforest-dark",
      "Everforest",
      "Everforest Light",
      "Everforest Dark",
      "everforest",
    ],
    classes: {
      light: "shiki-theme-everforest-light",
      dark: "shiki-theme-everforest-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-github",
    label: "GitHub",
    description: "Use GitHub Light in light mode and GitHub Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "github-light",
      "github-dark",
      "GitHub",
      "GitHub Light",
      "GitHub Dark",
      "github",
    ],
    classes: {
      light: "shiki-theme-github-light",
      dark: "shiki-theme-github-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-github-default",
    label: "GitHub Default",
    description:
      "Use GitHub Light Default in light mode and GitHub Dark Default in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "github-light-default",
      "github-dark-default",
      "GitHub Default",
      "GitHub Light Default",
      "GitHub Dark Default",
      "github",
      "default",
    ],
    classes: {
      light: "shiki-theme-github-light-default",
      dark: "shiki-theme-github-dark-default",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-github-high-contrast",
    label: "GitHub High Contrast",
    description:
      "Use GitHub Light High Contrast in light mode and GitHub Dark High Contrast in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "github-light-high-contrast",
      "github-dark-high-contrast",
      "GitHub High Contrast",
      "GitHub Light High Contrast",
      "GitHub Dark High Contrast",
      "github",
      "high contrast",
      "contrast",
    ],
    classes: {
      light: "shiki-theme-github-light-high-contrast",
      dark: "shiki-theme-github-dark-high-contrast",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-gruvbox-hard",
    label: "Gruvbox Hard",
    description:
      "Use Gruvbox Light Hard in light mode and Gruvbox Dark Hard in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "gruvbox-light-hard",
      "gruvbox-dark-hard",
      "Gruvbox Hard",
      "Gruvbox Light Hard",
      "Gruvbox Dark Hard",
      "gruvbox",
      "hard",
    ],
    classes: {
      light: "shiki-theme-gruvbox-light-hard",
      dark: "shiki-theme-gruvbox-dark-hard",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-gruvbox-medium",
    label: "Gruvbox Medium",
    description:
      "Use Gruvbox Light Medium in light mode and Gruvbox Dark Medium in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "gruvbox-light-medium",
      "gruvbox-dark-medium",
      "Gruvbox Medium",
      "Gruvbox Light Medium",
      "Gruvbox Dark Medium",
      "gruvbox",
      "medium",
    ],
    classes: {
      light: "shiki-theme-gruvbox-light-medium",
      dark: "shiki-theme-gruvbox-dark-medium",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-gruvbox-soft",
    label: "Gruvbox Soft",
    description:
      "Use Gruvbox Light Soft in light mode and Gruvbox Dark Soft in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "gruvbox-light-soft",
      "gruvbox-dark-soft",
      "Gruvbox Soft",
      "Gruvbox Light Soft",
      "Gruvbox Dark Soft",
      "gruvbox",
      "soft",
    ],
    classes: {
      light: "shiki-theme-gruvbox-light-soft",
      dark: "shiki-theme-gruvbox-dark-soft",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-kanagawa-dragon",
    label: "Kanagawa Dragon",
    description:
      "Use Kanagawa Lotus in light mode and Kanagawa Dragon in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "kanagawa-lotus",
      "kanagawa-dragon",
      "Kanagawa Dragon",
      "Kanagawa Lotus",
      "kanagawa",
      "lotus",
      "dragon",
    ],
    classes: {
      light: "shiki-theme-kanagawa-lotus",
      dark: "shiki-theme-kanagawa-dragon",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-kanagawa-wave",
    label: "Kanagawa Wave",
    description:
      "Use Kanagawa Lotus in light mode and Kanagawa Wave in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "kanagawa-lotus",
      "kanagawa-wave",
      "Kanagawa Wave",
      "Kanagawa Lotus",
      "kanagawa",
      "lotus",
      "wave",
    ],
    classes: {
      light: "shiki-theme-kanagawa-lotus",
      dark: "shiki-theme-kanagawa-wave",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-material-theme",
    label: "Material Theme",
    description:
      "Use Material Theme Lighter in light mode and Material Theme in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "material-theme-lighter",
      "material-theme",
      "Material Theme",
      "Material Theme Lighter",
      "material",
      "lighter",
    ],
    classes: {
      light: "shiki-theme-material-theme-lighter",
      dark: "shiki-theme-material-theme",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-material-theme-darker",
    label: "Material Theme Darker",
    description:
      "Use Material Theme Lighter in light mode and Material Theme Darker in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "material-theme-lighter",
      "material-theme-darker",
      "Material Theme Darker",
      "Material Theme Lighter",
      "material",
      "darker",
      "lighter",
    ],
    classes: {
      light: "shiki-theme-material-theme-lighter",
      dark: "shiki-theme-material-theme-darker",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-material-theme-ocean",
    label: "Material Theme Ocean",
    description:
      "Use Material Theme Lighter in light mode and Material Theme Ocean in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "material-theme-lighter",
      "material-theme-ocean",
      "Material Theme Ocean",
      "Material Theme Lighter",
      "material",
      "ocean",
      "lighter",
    ],
    classes: {
      light: "shiki-theme-material-theme-lighter",
      dark: "shiki-theme-material-theme-ocean",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-material-theme-palenight",
    label: "Material Theme Palenight",
    description:
      "Use Material Theme Lighter in light mode and Material Theme Palenight in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "material-theme-lighter",
      "material-theme-palenight",
      "Material Theme Palenight",
      "Material Theme Lighter",
      "material",
      "palenight",
      "lighter",
    ],
    classes: {
      light: "shiki-theme-material-theme-lighter",
      dark: "shiki-theme-material-theme-palenight",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-min",
    label: "Min",
    description: "Use Min Light in light mode and Min Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "min-light",
      "min-dark",
      "Min",
      "Min Light",
      "Min Dark",
      "min",
      "minimal",
    ],
    classes: {
      light: "shiki-theme-min-light",
      dark: "shiki-theme-min-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-night-owl",
    label: "Night Owl",
    description:
      "Use Night Owl Light in light mode and Night Owl in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "night-owl-light",
      "night-owl",
      "Night Owl",
      "Night Owl Light",
      "night owl",
    ],
    classes: {
      light: "shiki-theme-night-owl-light",
      dark: "shiki-theme-night-owl",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-one",
    label: "One",
    description: "Use One Light in light mode and One Dark Pro in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "one-light",
      "one-dark-pro",
      "One",
      "One Light",
      "One Dark Pro",
      "one",
      "atom",
    ],
    classes: {
      light: "shiki-theme-one-light",
      dark: "shiki-theme-one-dark-pro",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-plus",
    label: "Plus",
    description: "Use Light Plus in light mode and Dark Plus in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "light-plus",
      "dark-plus",
      "Plus",
      "Light Plus",
      "Dark Plus",
      "plus",
      "vscode",
      "visual studio code",
    ],
    classes: {
      light: "shiki-theme-light-plus",
      dark: "shiki-theme-dark-plus",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-rose-pine",
    label: "Rosé Pine",
    description: "Use Rosé Pine Dawn in light mode and Rosé Pine in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "rose-pine-dawn",
      "rose-pine",
      "Rosé Pine",
      "Rosé Pine Dawn",
      "rose pine",
      "rosé pine",
      "dawn",
    ],
    classes: {
      light: "shiki-theme-rose-pine-dawn",
      dark: "shiki-theme-rose-pine",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-rose-pine-moon",
    label: "Rosé Pine Moon",
    description:
      "Use Rosé Pine Dawn in light mode and Rosé Pine Moon in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "rose-pine-dawn",
      "rose-pine-moon",
      "Rosé Pine Moon",
      "Rosé Pine Dawn",
      "rose pine",
      "rosé pine",
      "moon",
      "dawn",
    ],
    classes: {
      light: "shiki-theme-rose-pine-dawn",
      dark: "shiki-theme-rose-pine-moon",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-slack",
    label: "Slack",
    description: "Use Slack Ochin in light mode and Slack Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "slack-ochin",
      "slack-dark",
      "Slack",
      "Slack Ochin",
      "Slack Dark",
      "slack",
      "ochin",
    ],
    classes: {
      light: "shiki-theme-slack-ochin",
      dark: "shiki-theme-slack-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-solarized",
    label: "Solarized",
    description:
      "Use Solarized Light in light mode and Solarized Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "solarized-light",
      "solarized-dark",
      "Solarized",
      "Solarized Light",
      "Solarized Dark",
      "solarized",
    ],
    classes: {
      light: "shiki-theme-solarized-light",
      dark: "shiki-theme-solarized-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-vitesse",
    label: "Vitesse",
    description:
      "Use Vitesse Light in light mode and Vitesse Dark in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "vitesse-light",
      "vitesse-dark",
      "Vitesse",
      "Vitesse Light",
      "Vitesse Dark",
      "vitesse",
    ],
    classes: {
      light: "shiki-theme-vitesse-light",
      dark: "shiki-theme-vitesse-dark",
    },
    selectorModes: ["auto"],
  },
  {
    id: "shiki-pair-vitesse-black",
    label: "Vitesse Black",
    description:
      "Use Vitesse Light in light mode and Vitesse Black in dark mode.",
    keywords: [
      "shiki",
      "auto",
      "system",
      "light",
      "dark",
      "vitesse-light",
      "vitesse-black",
      "Vitesse Black",
      "Vitesse Light",
      "vitesse",
      "black",
    ],
    classes: {
      light: "shiki-theme-vitesse-light",
      dark: "shiki-theme-vitesse-black",
    },
    selectorModes: ["auto"],
  },
] as const
export const SHIKI_BUNDLED_THEME_DEFINITIONS = [
  {
    id: "shiki-andromeeda",
    label: "Andromeeda",
    description: "Use Andromeeda theme (dark).",
    keywords: ["shiki", "andromeeda", "Andromeeda", "andromeeda", "dark"],
    classes: {
      light: "shiki-theme-andromeeda",
      dark: "shiki-theme-andromeeda",
    },
    mode: "dark",
  },
  {
    id: "shiki-aurora-x",
    label: "Aurora X",
    description: "Use Aurora X theme (dark).",
    keywords: ["shiki", "aurora-x", "Aurora X", "aurora-x", "dark"],
    classes: { light: "shiki-theme-aurora-x", dark: "shiki-theme-aurora-x" },
    mode: "dark",
  },
  {
    id: "shiki-ayu-dark",
    label: "Ayu Dark",
    description: "Use Ayu Dark theme (dark).",
    keywords: ["shiki", "ayu-dark", "Ayu Dark", "ayu-dark", "dark"],
    classes: { light: "shiki-theme-ayu-dark", dark: "shiki-theme-ayu-dark" },
    mode: "dark",
  },
  {
    id: "shiki-ayu-light",
    label: "Ayu Light",
    description: "Use Ayu Light theme (light).",
    keywords: ["shiki", "ayu-light", "Ayu Light", "ayu-light", "light"],
    classes: { light: "shiki-theme-ayu-light", dark: "shiki-theme-ayu-light" },
    mode: "light",
  },
  {
    id: "shiki-ayu-mirage",
    label: "Ayu Mirage",
    description: "Use Ayu Mirage theme (dark).",
    keywords: ["shiki", "ayu-mirage", "Ayu Mirage", "ayu-mirage", "dark"],
    classes: {
      light: "shiki-theme-ayu-mirage",
      dark: "shiki-theme-ayu-mirage",
    },
    mode: "dark",
  },
  {
    id: "shiki-catppuccin-frappe",
    label: "Catppuccin Frappé",
    description: "Use Catppuccin Frappé theme (dark).",
    keywords: [
      "shiki",
      "catppuccin-frappe",
      "Catppuccin Frappé",
      "catppuccin-frappe",
      "dark",
    ],
    classes: {
      light: "shiki-theme-catppuccin-frappe",
      dark: "shiki-theme-catppuccin-frappe",
    },
    mode: "dark",
  },
  {
    id: "shiki-catppuccin-latte",
    label: "Catppuccin Latte",
    description: "Use Catppuccin Latte theme (light).",
    keywords: [
      "shiki",
      "catppuccin-latte",
      "Catppuccin Latte",
      "catppuccin-latte",
      "light",
    ],
    classes: {
      light: "shiki-theme-catppuccin-latte",
      dark: "shiki-theme-catppuccin-latte",
    },
    mode: "light",
  },
  {
    id: "shiki-catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    description: "Use Catppuccin Macchiato theme (dark).",
    keywords: [
      "shiki",
      "catppuccin-macchiato",
      "Catppuccin Macchiato",
      "catppuccin-macchiato",
      "dark",
    ],
    classes: {
      light: "shiki-theme-catppuccin-macchiato",
      dark: "shiki-theme-catppuccin-macchiato",
    },
    mode: "dark",
  },
  {
    id: "shiki-catppuccin-mocha",
    label: "Catppuccin Mocha",
    description: "Use Catppuccin Mocha theme (dark).",
    keywords: [
      "shiki",
      "catppuccin-mocha",
      "Catppuccin Mocha",
      "catppuccin-mocha",
      "dark",
    ],
    classes: {
      light: "shiki-theme-catppuccin-mocha",
      dark: "shiki-theme-catppuccin-mocha",
    },
    mode: "dark",
  },
  {
    id: "shiki-dark-plus",
    label: "Dark Plus",
    description: "Use Dark Plus theme (dark).",
    keywords: ["shiki", "dark-plus", "Dark Plus", "dark-plus", "dark"],
    classes: { light: "shiki-theme-dark-plus", dark: "shiki-theme-dark-plus" },
    mode: "dark",
  },
  {
    id: "shiki-dracula",
    label: "Dracula Theme",
    description: "Use Dracula Theme theme (dark).",
    keywords: ["shiki", "dracula", "Dracula Theme", "dracula", "dark"],
    classes: { light: "shiki-theme-dracula", dark: "shiki-theme-dracula" },
    mode: "dark",
  },
  {
    id: "shiki-dracula-soft",
    label: "Dracula Theme Soft",
    description: "Use Dracula Theme Soft theme (dark).",
    keywords: [
      "shiki",
      "dracula-soft",
      "Dracula Theme Soft",
      "dracula-soft",
      "dark",
    ],
    classes: {
      light: "shiki-theme-dracula-soft",
      dark: "shiki-theme-dracula-soft",
    },
    mode: "dark",
  },
  {
    id: "shiki-everforest-dark",
    label: "Everforest Dark",
    description: "Use Everforest Dark theme (dark).",
    keywords: [
      "shiki",
      "everforest-dark",
      "Everforest Dark",
      "everforest-dark",
      "dark",
    ],
    classes: {
      light: "shiki-theme-everforest-dark",
      dark: "shiki-theme-everforest-dark",
    },
    mode: "dark",
  },
  {
    id: "shiki-everforest-light",
    label: "Everforest Light",
    description: "Use Everforest Light theme (light).",
    keywords: [
      "shiki",
      "everforest-light",
      "Everforest Light",
      "everforest-light",
      "light",
    ],
    classes: {
      light: "shiki-theme-everforest-light",
      dark: "shiki-theme-everforest-light",
    },
    mode: "light",
  },
  {
    id: "shiki-github-dark",
    label: "GitHub Dark",
    description: "Use GitHub Dark theme (dark).",
    keywords: ["shiki", "github-dark", "GitHub Dark", "github-dark", "dark"],
    classes: {
      light: "shiki-theme-github-dark",
      dark: "shiki-theme-github-dark",
    },
    mode: "dark",
  },
  {
    id: "shiki-github-dark-default",
    label: "GitHub Dark Default",
    description: "Use GitHub Dark Default theme (dark).",
    keywords: [
      "shiki",
      "github-dark-default",
      "GitHub Dark Default",
      "github-dark-default",
      "dark",
    ],
    classes: {
      light: "shiki-theme-github-dark-default",
      dark: "shiki-theme-github-dark-default",
    },
    mode: "dark",
  },
  {
    id: "shiki-github-dark-dimmed",
    label: "GitHub Dark Dimmed",
    description: "Use GitHub Dark Dimmed theme (dark).",
    keywords: [
      "shiki",
      "github-dark-dimmed",
      "GitHub Dark Dimmed",
      "github-dark-dimmed",
      "dark",
    ],
    classes: {
      light: "shiki-theme-github-dark-dimmed",
      dark: "shiki-theme-github-dark-dimmed",
    },
    mode: "dark",
  },
  {
    id: "shiki-github-dark-high-contrast",
    label: "GitHub Dark High Contrast",
    description: "Use GitHub Dark High Contrast theme (dark).",
    keywords: [
      "shiki",
      "github-dark-high-contrast",
      "GitHub Dark High Contrast",
      "github-dark-high-contrast",
      "dark",
    ],
    classes: {
      light: "shiki-theme-github-dark-high-contrast",
      dark: "shiki-theme-github-dark-high-contrast",
    },
    mode: "dark",
  },
  {
    id: "shiki-github-light",
    label: "GitHub Light",
    description: "Use GitHub Light theme (light).",
    keywords: [
      "shiki",
      "github-light",
      "GitHub Light",
      "github-light",
      "light",
    ],
    classes: {
      light: "shiki-theme-github-light",
      dark: "shiki-theme-github-light",
    },
    mode: "light",
  },
  {
    id: "shiki-github-light-default",
    label: "GitHub Light Default",
    description: "Use GitHub Light Default theme (light).",
    keywords: [
      "shiki",
      "github-light-default",
      "GitHub Light Default",
      "github-light-default",
      "light",
    ],
    classes: {
      light: "shiki-theme-github-light-default",
      dark: "shiki-theme-github-light-default",
    },
    mode: "light",
  },
  {
    id: "shiki-github-light-high-contrast",
    label: "GitHub Light High Contrast",
    description: "Use GitHub Light High Contrast theme (light).",
    keywords: [
      "shiki",
      "github-light-high-contrast",
      "GitHub Light High Contrast",
      "github-light-high-contrast",
      "light",
    ],
    classes: {
      light: "shiki-theme-github-light-high-contrast",
      dark: "shiki-theme-github-light-high-contrast",
    },
    mode: "light",
  },
  {
    id: "shiki-gruvbox-dark-hard",
    label: "Gruvbox Dark Hard",
    description: "Use Gruvbox Dark Hard theme (dark).",
    keywords: [
      "shiki",
      "gruvbox-dark-hard",
      "Gruvbox Dark Hard",
      "gruvbox-dark-hard",
      "dark",
    ],
    classes: {
      light: "shiki-theme-gruvbox-dark-hard",
      dark: "shiki-theme-gruvbox-dark-hard",
    },
    mode: "dark",
  },
  {
    id: "shiki-gruvbox-dark-medium",
    label: "Gruvbox Dark Medium",
    description: "Use Gruvbox Dark Medium theme (dark).",
    keywords: [
      "shiki",
      "gruvbox-dark-medium",
      "Gruvbox Dark Medium",
      "gruvbox-dark-medium",
      "dark",
    ],
    classes: {
      light: "shiki-theme-gruvbox-dark-medium",
      dark: "shiki-theme-gruvbox-dark-medium",
    },
    mode: "dark",
  },
  {
    id: "shiki-gruvbox-dark-soft",
    label: "Gruvbox Dark Soft",
    description: "Use Gruvbox Dark Soft theme (dark).",
    keywords: [
      "shiki",
      "gruvbox-dark-soft",
      "Gruvbox Dark Soft",
      "gruvbox-dark-soft",
      "dark",
    ],
    classes: {
      light: "shiki-theme-gruvbox-dark-soft",
      dark: "shiki-theme-gruvbox-dark-soft",
    },
    mode: "dark",
  },
  {
    id: "shiki-gruvbox-light-hard",
    label: "Gruvbox Light Hard",
    description: "Use Gruvbox Light Hard theme (light).",
    keywords: [
      "shiki",
      "gruvbox-light-hard",
      "Gruvbox Light Hard",
      "gruvbox-light-hard",
      "light",
    ],
    classes: {
      light: "shiki-theme-gruvbox-light-hard",
      dark: "shiki-theme-gruvbox-light-hard",
    },
    mode: "light",
  },
  {
    id: "shiki-gruvbox-light-medium",
    label: "Gruvbox Light Medium",
    description: "Use Gruvbox Light Medium theme (light).",
    keywords: [
      "shiki",
      "gruvbox-light-medium",
      "Gruvbox Light Medium",
      "gruvbox-light-medium",
      "light",
    ],
    classes: {
      light: "shiki-theme-gruvbox-light-medium",
      dark: "shiki-theme-gruvbox-light-medium",
    },
    mode: "light",
  },
  {
    id: "shiki-gruvbox-light-soft",
    label: "Gruvbox Light Soft",
    description: "Use Gruvbox Light Soft theme (light).",
    keywords: [
      "shiki",
      "gruvbox-light-soft",
      "Gruvbox Light Soft",
      "gruvbox-light-soft",
      "light",
    ],
    classes: {
      light: "shiki-theme-gruvbox-light-soft",
      dark: "shiki-theme-gruvbox-light-soft",
    },
    mode: "light",
  },
  {
    id: "shiki-horizon",
    label: "Horizon",
    description: "Use Horizon theme (dark).",
    keywords: ["shiki", "horizon", "Horizon", "horizon", "dark"],
    classes: { light: "shiki-theme-horizon", dark: "shiki-theme-horizon" },
    mode: "dark",
  },
  {
    id: "shiki-horizon-bright",
    label: "Horizon Bright",
    description: "Use Horizon Bright theme (dark).",
    keywords: [
      "shiki",
      "horizon-bright",
      "Horizon Bright",
      "horizon-bright",
      "dark",
    ],
    classes: {
      light: "shiki-theme-horizon-bright",
      dark: "shiki-theme-horizon-bright",
    },
    mode: "dark",
  },
  {
    id: "shiki-houston",
    label: "Houston",
    description: "Use Houston theme (dark).",
    keywords: ["shiki", "houston", "Houston", "houston", "dark"],
    classes: { light: "shiki-theme-houston", dark: "shiki-theme-houston" },
    mode: "dark",
  },
  {
    id: "shiki-kanagawa-dragon",
    label: "Kanagawa Dragon",
    description: "Use Kanagawa Dragon theme (dark).",
    keywords: [
      "shiki",
      "kanagawa-dragon",
      "Kanagawa Dragon",
      "kanagawa-dragon",
      "dark",
    ],
    classes: {
      light: "shiki-theme-kanagawa-dragon",
      dark: "shiki-theme-kanagawa-dragon",
    },
    mode: "dark",
  },
  {
    id: "shiki-kanagawa-lotus",
    label: "Kanagawa Lotus",
    description: "Use Kanagawa Lotus theme (light).",
    keywords: [
      "shiki",
      "kanagawa-lotus",
      "Kanagawa Lotus",
      "kanagawa-lotus",
      "light",
    ],
    classes: {
      light: "shiki-theme-kanagawa-lotus",
      dark: "shiki-theme-kanagawa-lotus",
    },
    mode: "light",
  },
  {
    id: "shiki-kanagawa-wave",
    label: "Kanagawa Wave",
    description: "Use Kanagawa Wave theme (dark).",
    keywords: [
      "shiki",
      "kanagawa-wave",
      "Kanagawa Wave",
      "kanagawa-wave",
      "dark",
    ],
    classes: {
      light: "shiki-theme-kanagawa-wave",
      dark: "shiki-theme-kanagawa-wave",
    },
    mode: "dark",
  },
  {
    id: "shiki-laserwave",
    label: "LaserWave",
    description: "Use LaserWave theme (dark).",
    keywords: ["shiki", "laserwave", "LaserWave", "laserwave", "dark"],
    classes: { light: "shiki-theme-laserwave", dark: "shiki-theme-laserwave" },
    mode: "dark",
  },
  {
    id: "shiki-light-plus",
    label: "Light Plus",
    description: "Use Light Plus theme (light).",
    keywords: ["shiki", "light-plus", "Light Plus", "light-plus", "light"],
    classes: {
      light: "shiki-theme-light-plus",
      dark: "shiki-theme-light-plus",
    },
    mode: "light",
  },
  {
    id: "shiki-material-theme",
    label: "Material Theme",
    description: "Use Material Theme theme (dark).",
    keywords: [
      "shiki",
      "material-theme",
      "Material Theme",
      "material-theme",
      "dark",
    ],
    classes: {
      light: "shiki-theme-material-theme",
      dark: "shiki-theme-material-theme",
    },
    mode: "dark",
  },
  {
    id: "shiki-material-theme-darker",
    label: "Material Theme Darker",
    description: "Use Material Theme Darker theme (dark).",
    keywords: [
      "shiki",
      "material-theme-darker",
      "Material Theme Darker",
      "material-theme-darker",
      "dark",
    ],
    classes: {
      light: "shiki-theme-material-theme-darker",
      dark: "shiki-theme-material-theme-darker",
    },
    mode: "dark",
  },
  {
    id: "shiki-material-theme-lighter",
    label: "Material Theme Lighter",
    description: "Use Material Theme Lighter theme (light).",
    keywords: [
      "shiki",
      "material-theme-lighter",
      "Material Theme Lighter",
      "material-theme-lighter",
      "light",
    ],
    classes: {
      light: "shiki-theme-material-theme-lighter",
      dark: "shiki-theme-material-theme-lighter",
    },
    mode: "light",
  },
  {
    id: "shiki-material-theme-ocean",
    label: "Material Theme Ocean",
    description: "Use Material Theme Ocean theme (dark).",
    keywords: [
      "shiki",
      "material-theme-ocean",
      "Material Theme Ocean",
      "material-theme-ocean",
      "dark",
    ],
    classes: {
      light: "shiki-theme-material-theme-ocean",
      dark: "shiki-theme-material-theme-ocean",
    },
    mode: "dark",
  },
  {
    id: "shiki-material-theme-palenight",
    label: "Material Theme Palenight",
    description: "Use Material Theme Palenight theme (dark).",
    keywords: [
      "shiki",
      "material-theme-palenight",
      "Material Theme Palenight",
      "material-theme-palenight",
      "dark",
    ],
    classes: {
      light: "shiki-theme-material-theme-palenight",
      dark: "shiki-theme-material-theme-palenight",
    },
    mode: "dark",
  },
  {
    id: "shiki-min-dark",
    label: "Min Dark",
    description: "Use Min Dark theme (dark).",
    keywords: ["shiki", "min-dark", "Min Dark", "min-dark", "dark"],
    classes: { light: "shiki-theme-min-dark", dark: "shiki-theme-min-dark" },
    mode: "dark",
  },
  {
    id: "shiki-min-light",
    label: "Min Light",
    description: "Use Min Light theme (light).",
    keywords: ["shiki", "min-light", "Min Light", "min-light", "light"],
    classes: { light: "shiki-theme-min-light", dark: "shiki-theme-min-light" },
    mode: "light",
  },
  {
    id: "shiki-monokai",
    label: "Monokai",
    description: "Use Monokai theme (dark).",
    keywords: ["shiki", "monokai", "Monokai", "monokai", "dark"],
    classes: { light: "shiki-theme-monokai", dark: "shiki-theme-monokai" },
    mode: "dark",
  },
  {
    id: "shiki-night-owl",
    label: "Night Owl",
    description: "Use Night Owl theme (dark).",
    keywords: ["shiki", "night-owl", "Night Owl", "night-owl", "dark"],
    classes: { light: "shiki-theme-night-owl", dark: "shiki-theme-night-owl" },
    mode: "dark",
  },
  {
    id: "shiki-night-owl-light",
    label: "Night Owl Light",
    description: "Use Night Owl Light theme (light).",
    keywords: [
      "shiki",
      "night-owl-light",
      "Night Owl Light",
      "night-owl-light",
      "light",
    ],
    classes: {
      light: "shiki-theme-night-owl-light",
      dark: "shiki-theme-night-owl-light",
    },
    mode: "light",
  },
  {
    id: "shiki-nord",
    label: "Nord",
    description: "Use Nord theme (dark).",
    keywords: ["shiki", "nord", "Nord", "nord", "dark"],
    classes: { light: "shiki-theme-nord", dark: "shiki-theme-nord" },
    mode: "dark",
  },
  {
    id: "shiki-one-dark-pro",
    label: "One Dark Pro",
    description: "Use One Dark Pro theme (dark).",
    keywords: ["shiki", "one-dark-pro", "One Dark Pro", "one-dark-pro", "dark"],
    classes: {
      light: "shiki-theme-one-dark-pro",
      dark: "shiki-theme-one-dark-pro",
    },
    mode: "dark",
  },
  {
    id: "shiki-one-light",
    label: "One Light",
    description: "Use One Light theme (light).",
    keywords: ["shiki", "one-light", "One Light", "one-light", "light"],
    classes: { light: "shiki-theme-one-light", dark: "shiki-theme-one-light" },
    mode: "light",
  },
  {
    id: "shiki-plastic",
    label: "Plastic",
    description: "Use Plastic theme (dark).",
    keywords: ["shiki", "plastic", "Plastic", "plastic", "dark"],
    classes: { light: "shiki-theme-plastic", dark: "shiki-theme-plastic" },
    mode: "dark",
  },
  {
    id: "shiki-poimandres",
    label: "Poimandres",
    description: "Use Poimandres theme (dark).",
    keywords: ["shiki", "poimandres", "Poimandres", "poimandres", "dark"],
    classes: {
      light: "shiki-theme-poimandres",
      dark: "shiki-theme-poimandres",
    },
    mode: "dark",
  },
  {
    id: "shiki-red",
    label: "Red",
    description: "Use Red theme (dark).",
    keywords: ["shiki", "red", "Red", "red", "dark"],
    classes: { light: "shiki-theme-red", dark: "shiki-theme-red" },
    mode: "dark",
  },
  {
    id: "shiki-rose-pine",
    label: "Rosé Pine",
    description: "Use Rosé Pine theme (dark).",
    keywords: ["shiki", "rose-pine", "Rosé Pine", "rose-pine", "dark"],
    classes: { light: "shiki-theme-rose-pine", dark: "shiki-theme-rose-pine" },
    mode: "dark",
  },
  {
    id: "shiki-rose-pine-dawn",
    label: "Rosé Pine Dawn",
    description: "Use Rosé Pine Dawn theme (light).",
    keywords: [
      "shiki",
      "rose-pine-dawn",
      "Rosé Pine Dawn",
      "rose-pine-dawn",
      "light",
    ],
    classes: {
      light: "shiki-theme-rose-pine-dawn",
      dark: "shiki-theme-rose-pine-dawn",
    },
    mode: "light",
  },
  {
    id: "shiki-rose-pine-moon",
    label: "Rosé Pine Moon",
    description: "Use Rosé Pine Moon theme (dark).",
    keywords: [
      "shiki",
      "rose-pine-moon",
      "Rosé Pine Moon",
      "rose-pine-moon",
      "dark",
    ],
    classes: {
      light: "shiki-theme-rose-pine-moon",
      dark: "shiki-theme-rose-pine-moon",
    },
    mode: "dark",
  },
  {
    id: "shiki-slack-dark",
    label: "Slack Dark",
    description: "Use Slack Dark theme (dark).",
    keywords: ["shiki", "slack-dark", "Slack Dark", "slack-dark", "dark"],
    classes: {
      light: "shiki-theme-slack-dark",
      dark: "shiki-theme-slack-dark",
    },
    mode: "dark",
  },
  {
    id: "shiki-slack-ochin",
    label: "Slack Ochin",
    description: "Use Slack Ochin theme (light).",
    keywords: ["shiki", "slack-ochin", "Slack Ochin", "slack-ochin", "light"],
    classes: {
      light: "shiki-theme-slack-ochin",
      dark: "shiki-theme-slack-ochin",
    },
    mode: "light",
  },
  {
    id: "shiki-snazzy-light",
    label: "Snazzy Light",
    description: "Use Snazzy Light theme (light).",
    keywords: [
      "shiki",
      "snazzy-light",
      "Snazzy Light",
      "snazzy-light",
      "light",
    ],
    classes: {
      light: "shiki-theme-snazzy-light",
      dark: "shiki-theme-snazzy-light",
    },
    mode: "light",
  },
  {
    id: "shiki-solarized-dark",
    label: "Solarized Dark",
    description: "Use Solarized Dark theme (dark).",
    keywords: [
      "shiki",
      "solarized-dark",
      "Solarized Dark",
      "solarized-dark",
      "dark",
    ],
    classes: {
      light: "shiki-theme-solarized-dark",
      dark: "shiki-theme-solarized-dark",
    },
    mode: "dark",
  },
  {
    id: "shiki-solarized-light",
    label: "Solarized Light",
    description: "Use Solarized Light theme (light).",
    keywords: [
      "shiki",
      "solarized-light",
      "Solarized Light",
      "solarized-light",
      "light",
    ],
    classes: {
      light: "shiki-theme-solarized-light",
      dark: "shiki-theme-solarized-light",
    },
    mode: "light",
  },
  {
    id: "shiki-synthwave-84",
    label: "Synthwave '84",
    description: "Use Synthwave '84 theme (dark).",
    keywords: [
      "shiki",
      "synthwave-84",
      "Synthwave '84",
      "synthwave-84",
      "dark",
    ],
    classes: {
      light: "shiki-theme-synthwave-84",
      dark: "shiki-theme-synthwave-84",
    },
    mode: "dark",
  },
  {
    id: "shiki-tokyo-night",
    label: "Tokyo Night",
    description: "Use Tokyo Night theme (dark).",
    keywords: ["shiki", "tokyo-night", "Tokyo Night", "tokyo-night", "dark"],
    classes: {
      light: "shiki-theme-tokyo-night",
      dark: "shiki-theme-tokyo-night",
    },
    mode: "dark",
  },
  {
    id: "shiki-vesper",
    label: "Vesper",
    description: "Use Vesper theme (dark).",
    keywords: ["shiki", "vesper", "Vesper", "vesper", "dark"],
    classes: { light: "shiki-theme-vesper", dark: "shiki-theme-vesper" },
    mode: "dark",
  },
  {
    id: "shiki-vitesse-black",
    label: "Vitesse Black",
    description: "Use Vitesse Black theme (dark).",
    keywords: [
      "shiki",
      "vitesse-black",
      "Vitesse Black",
      "vitesse-black",
      "dark",
    ],
    classes: {
      light: "shiki-theme-vitesse-black",
      dark: "shiki-theme-vitesse-black",
    },
    mode: "dark",
  },
  {
    id: "shiki-vitesse-dark",
    label: "Vitesse Dark",
    description: "Use Vitesse Dark theme (dark).",
    keywords: ["shiki", "vitesse-dark", "Vitesse Dark", "vitesse-dark", "dark"],
    classes: {
      light: "shiki-theme-vitesse-dark",
      dark: "shiki-theme-vitesse-dark",
    },
    mode: "dark",
  },
  {
    id: "shiki-vitesse-light",
    label: "Vitesse Light",
    description: "Use Vitesse Light theme (light).",
    keywords: [
      "shiki",
      "vitesse-light",
      "Vitesse Light",
      "vitesse-light",
      "light",
    ],
    classes: {
      light: "shiki-theme-vitesse-light",
      dark: "shiki-theme-vitesse-light",
    },
    mode: "light",
  },
] as const
